let l=32;
var r={Db:[{g:[0,0,140,0,0,0,140,0,0,255,158,158,158,0,0,0,0,51,2,1,2,58,239,0,32,88,1,157,2],p:[1,1,1,1],c:[{n:[161,,,,,,,,,,,,,,,,163,,,,,,,,159],f:[]}]},{g:[0,91,128,0,0,95,128,12,0,0,12,0,72,0,0,0,0,0,0,0,2,255,0,0,32,83,3,130,4],p:[1,1,2,1],c:[{n:[144,,151,,149,,147,,146,,147,,146,,144,,144,,151,,149,,147,,146,,147,,146,,144],f:[]},{n:[156,,163,,161,,159,,158,,159,,158,,156,,156,,163,,161,,159,,158,,159,,158,,168],f:[]}]},{g:[0,16,133,0,0,28,126,12,0,0,2,0,60,0,0,0,0,0,0,0,2,91,0,0,32,47,3,157,
2],p:[1,2,1,2],c:[{n:[144,,151,,149,,147,,146,,147,,146,,144,,144,,151,,149,,147,,146,,147,,146,,144],f:[]},{n:[168,,175,,173,,171,,170,,171,,170,,168,,168,,175,,173,,171,,170,,171,,170,,168],f:[]}]},{g:[0,255,116,79,0,255,116,0,83,0,4,6,69,52,0,0,0,0,0,0,2,14,0,0,32,0,0,0,0],p:[1,1,1,1],c:[{n:[144,,151,,149,,147,,146,,147,,146,,144,,144,,151,,149,,147,,146,,147,,146,,144,,,159,,,,159,,,,159,,,,,,,,,,,,159,,159],f:[]}]}],kb:8269,jb:32,qb:3,wb:4},aa=[{g:"ff",r:"m",m:!1,l:0,o:0},{g:"ww",r:"m",m:!1,
l:0,o:0},{g:"ee",r:"m",m:!1,l:0,o:0},{g:"ii",r:"m",m:!1,l:0,o:0},{g:"zz",r:"m",m:!1,l:0,o:0},{g:"ll",r:"m",m:!1,l:0,o:0},{g:"dd",r:"m",m:!1,l:0,o:0},{g:"mf",r:"f",m:!0,l:2,o:0},{g:"mw",r:"w",m:!0,l:2,o:0},{g:"me",r:"e",m:!0,l:2,o:0},{g:"mi",r:"i",m:!0,l:2,o:0},{g:"mz",r:"z",m:!0,l:2,o:0},{g:"ml",r:"l",m:!0,l:2,o:0},{g:"md",r:"d",m:!0,l:2,o:0},{g:"mff",r:"f",m:!0,l:4,o:0},{g:"mww",r:"w",m:!0,l:4,o:0},{g:"mee",r:"e",m:!0,l:4,o:0},{g:"mii",r:"i",m:!0,l:4,o:0},{g:"mzz",r:"z",m:!0,l:4,o:0},{g:"mll",r:"l",
m:!0,l:4,o:0},{g:"mfff",r:"f",m:!0,l:8,o:0},{g:"mwww",r:"w",m:!0,l:8,o:0},{g:"meee",r:"e",m:!0,l:8,o:0},{g:"miii",r:"i",m:!0,l:8,o:0},{g:"mzzz",r:"z",m:!0,l:8,o:0},{g:"mlll",r:"l",m:!0,l:8,o:0},{g:"mddd",r:"d",m:!0,l:8,o:0},{g:"mfi",r:"f",m:!0,l:3,o:0},{g:"mfe",r:"f",m:!0,l:4,o:0},{g:"mwi",r:"w",m:!0,l:3,o:0},{g:"mwe",r:"w",m:!0,l:3,o:0}];function ha(a,b,c){const d=[];for(let e=0;70>e;e++){const f=2*Math.PI*e/70;d.push({x:a+c*Math.cos(f),y:b+c*Math.sin(f)})}return d}
function ia(a){function b(B){return t(d,B[0],B[1],B[2],B[3])}function c(B,D,J,F,E){var x=y(d);x.h.drawImage(k,e.Ka[0],e.Ka[1]+(B?-2:0));x.h.drawImage(m,e.Pa[0],e.Pa[1]+(D?-2:0));J?x.h.drawImage(g,e.pa[0],e.pa[1]+4):x.h.drawImage(f,e.pa[0],e.pa[1]);F?x.h.drawImage(q,e.ia[0],e.ia[1]-4):x.h.drawImage(n,e.ia[0],e.ia[1]);E?x.h.drawImage(A,e.na[0],e.na[1]-4):x.h.drawImage(p,e.na[0],e.na[1]);return x}var d=y(a.Ua);a=[];var e={pa:[27,20,4,6],Ka:[7,29,8,3],Pa:[17,29,8,3],ia:[5,15,5,7],na:[22,15,5,7]},f=b(e.pa),
g=z(f),k=b(e.Ka),m=b(e.Pa),n=b(e.ia),q=z(n),p=b(e.na),A=z(p);for(var v in e){var u=e[v];d.h.clearRect(u[0],u[1],u[2],u[3])}v=[{$:0,ba:0,ca:0,Z:0,aa:0},{$:0,ba:0,ca:0,Z:0,aa:0},{$:1,ba:0,ca:0,Z:0,aa:1},{$:1,ba:0,ca:1,Z:0,aa:0},{$:0,ba:1,ca:0,Z:1,aa:0},{$:0,ba:1,ca:1,Z:0,aa:0}];for(let B in v)u=v[B],u=c(u.$,u.ba,u.ca,u.Z,u.aa),a.push(u);return a}class ja{constructor(a){a=y(a);a=C(a,b=>""==b||"#fff"==b||"#ffffff"==b?null:b);a=H(a,1);this.Ua=t(a,0,0,32,32);t(a,32,0,32,32);this.gb=t(a,0,32,64,64)}}
class ka{constructor(a,b,c,d,e){this.x=a;this.y=0;this.w=b;this.i=c;this.A=d;this.onclick=e}Y(a){var b=a.x;a=a.y;if(b>=this.x&&b<=this.x+this.w&&a>=this.y&&a<=this.y+this.i){if(this.onclick)this.onclick(this);return!0}return!1}L(a){a.save();a.strokeStyle="#f00";a.lineWidth=2;a.strokeRect(this.x,this.y,this.w,this.i);a.restore();a.drawImage(this.A,this.x,this.y,this.w,this.i)}update(){}}
function la(a,b){let c=a[0],d=b[c[0]][c[1]];for(const e of a){const [f,g]=e;b[f][g]<d&&(c=e,d=b[f][g])}return c}function ma(a,b){const c=[b];for(;a.hasOwnProperty(`${b[0]}-${b[1]}`);)b=a[`${b[0]}-${b[1]}`],c.unshift(b);return c}function na(a,b,c){const d=[];0<b&&d.push([b-1,c]);b<a.rows-1&&d.push([b+1,c]);0<c&&d.push([b,c-1]);c<a.cols-1&&d.push([b,c+1]);return d}
function oa(a,b,c,d,e){b=Math.floor(b);c=Math.floor(c);d=Math.floor(d);e=Math.floor(e);const f=[],g=new Set,k={},m=Array(a.rows).fill(null).map(()=>Array(a.cols).fill(Infinity));m[b][c]=0;const n=Array(a.rows).fill(null).map(()=>Array(a.cols).fill(Infinity));n[b][c]=Math.abs(b-d)+Math.abs(c-e);for(f.push([b,c]);0<f.length;){b=la(f,n);const [q,p]=b;if(q===d&&p===e)return ma(k,b);f.splice(f.indexOf(b),1);g.add(`${q}-${p}`);c=na(a,q,p);for(const A of c){const [v,u]=A;g.has(`${v}-${u}`)||a.vb[v][u]||
(c=m[q][p]+1,c<m[v][u]&&(k[`${v}-${u}`]=b,m[v][u]=c,n[v][u]=c+(Math.abs(v-d)+Math.abs(u-e)),f.includes(A)||f.push(A)))}}return null}class pa{constructor(a){this.vb=a;this.rows=a.length;this.cols=a[0].length}}function ya(a=64,b=64){const c=K(a,b),d=c.h;d.fillStyle="#a67c52";d.fillRect(0,0,a,b);for(let e=0;e<a+b;e++){const f=M(0,a),g=M(0,b),k=M(2,5);d.globalAlpha=N(.15,.35);d.fillStyle=.5<N()?"#c2b280":"#7c5c36";d.beginPath();d.arc(f,g,k,0,2*Math.PI);d.fill()}d.globalAlpha=1;return c}
function za(a=64,b=64){const c=K(a,b),d=c.h;d.fillStyle="#b0a99f";d.fillRect(0,0,a,b);const e=a/4;b/=4;for(let f=0;4>f;f++)for(let g=0;4>g;g++){let k=g*e+(1===f%2?e/2:0);if(k+e>a)continue;let m=f*b;d.fillStyle=.5<N()?"#d6d2c4":"#a59e91";d.fillRect(k,m,e-2,b-2);d.strokeStyle="#8d867a";d.lineWidth=1;d.strokeRect(k,m,e-2,b-2)}d.globalAlpha=1;return c}
function Aa(a=64,b=64){const c=K(a,b),d=c.h;d.fillStyle="#639bff";d.fillRect(0,0,a,b);for(let e=0;e<a+b;e++){const f=M(0,a),g=M(0,b),k=M(2,6);d.globalAlpha=N(.15,.35);d.fillStyle="#a3d8ff";d.beginPath();d.arc(f,g,k,0,2*Math.PI);d.fill()}d.globalAlpha=1;return c}
function Ba(a=64){const b=document.createElement("canvas");b.width=b.height=a;const c=b.getContext("2d");c.fillStyle="#e6d3b3";c.fillRect(0,0,a,a);const d=["#d1bfa3","#c2ad8f","#b8a07d","#e0ceb0"],e=a/4*.9,f=a/3*.7;for(let g=0;3>g;g++)for(let k=0;4>k;k++){let m=k*a/4+g%2*a/8,n=g*a/3;c.beginPath();c.ellipse(m+e/2,n+f/2,e/2,f/2,0,0,2*Math.PI);c.fillStyle=d[Math.floor(Math.random()*d.length)];c.shadowColor="#bba98a";c.shadowBlur=4;c.fill();c.shadowBlur=0}c.globalAlpha=.08;c.fillStyle="#fff";c.beginPath();
c.arc(.7*a,.3*a,.25*a,0,2*Math.PI);c.fill();c.globalAlpha=1;return b}function Ca(a=64,b=64){const c=K(a,b),d=c.h;d.fillStyle="#4caf50";d.fillRect(0,0,a,b);for(let e=0;e<a+b;e++){const f=M(0,a),g=M(0,b),k=M(2,5);d.globalAlpha=N(.18,.38);d.fillStyle=.5<N()?"#81c784":"#388e3c";d.beginPath();d.arc(f,g,k,0,2*Math.PI);d.fill()}d.globalAlpha=1;return c}
function Da(a=64,b=64,c=8){var d=[O("\ud83c\udf39",12,1.3),O("\ud83c\udf37",12,1.3),O("\ud83c\udf3b",12,1.3),O("\ud83c\udf3c",12,1.3),O("\ud83c\udf31",12,1.3)];const e=K(a,b);var f=e.h,g=Ca(a,b);f.fillStyle="#4caf50";f.drawImage(g,0,0);for(g=0;g<c;g++)f.drawImage(d[M(0,d.length)],M(0,a-12),M(0,b-12));return e}
function Ea(a,b){var c=Da(64*l,64*l,l*l),d={};a.Za.map(f=>d[f.c]=f.j);a=C(b,f=>""==f?null:f);b=K(64*l,64*l);var e=b.h;e.drawImage(c,0,0);for(let f=0;64>f;f++)for(let g=0;64>g;g++)c=d[a[g][f]],void 0!=c&&e.drawImage(c,f*l,g*l);return b}function Fa(a,b){var c={};for(var d in b)c[b[d].c]=b[d].D;b=[];for(d=0;d<a.length;d++){b[d]=[];for(var e=0;e<a[d].length;e++){var f=c[a[e][d]];b[d][e]=void 0!=f&&0==f?0:1}}return b}
class Ga{constructor(a){this.M=a;this.ab=this.M.B.w;this.ch=this.M.B.i;var b=ya(l,l),c=za(l,l),d=Aa(l,l),e=O("\ud83c\udf33",l,1.3),f=O("\ud83c\udfe1",2*l,1.3),g=O("\ud83c\udfe0",2*l,1.3),k=O("\u26ea",3*l,1.3),m=O("\ud83c\udfeb",3*l,1.3),n=O("\ud83c\udff0",4*l,1.3),q=O("\ud83c\udfea",3*l,1.3),p=O("\u26fa",3*l,1.3),A=Ba(l);this.Za=[{c:"#99e550",D:0,G:"",j:void 0},{c:"#639bff",D:1,G:"",j:d},{c:"#6abe30",D:1,G:"",j:e},{c:"#76428a",D:1,G:"house1",j:f},{c:"#d77bba",D:1,G:"house2",j:g},{c:"#d9a066",D:0,
G:"",j:b},{c:"#767676",D:1,G:"",j:A},{c:"#df7126",D:1,G:"castle",j:n},{c:"#8f974a",D:1,G:"church",j:k},{c:"#fbf236",D:1,G:"townhall",j:m},{c:"#ac3232",D:1,G:"store",j:q},{c:"#663931",D:0,G:"",j:c},{c:"#524b24",D:1,G:"tent",j:p}];this.ob=C(a.Ca.gb,v=>""==v?null:v);this.map=Ea(this,a.Ca.gb);this.ib=Fa(this.ob,this.Za);this.Ab=new pa(this.ib)}L(a){let b=this.map,c;let d,e,f,g;var k=NaN-this.ch/2;c=NaN-this.ab/2;0>=c&&(c=0);0>=k&&(k=0);c+this.w>b.width&&(c=b.width-this.ab);k+this.i>b.height&&(k=b.height-
this.ch);d=f=this.w;e=g=this.i;a.drawImage(b,c,k,d,e,0,0,f,g)}}function Ha(a){var b=[];for(let c=2;5>=c;c++)b.push(a.qa[c]);return b}class Ia{constructor(a){this.qa=ia(a.Ca)}}function Ja(a){a.ka=r;a.La=r.qb;a.wa=0;a.ja=r.kb*r.jb*(a.La+1)*2;a.S=new Int32Array(a.ja)}
function Ka(a,b,c){Ja(a);var d=()=>{var e,f,g,k,m,n,q=new Int32Array(a.ja);const p=a.ka.Db[a.wa],A=a.ka.kb,v=a.ka.jb;let u=0,B=0;var D=!1;const J=[];for(g=0;g<=a.La;++g){var F=p.p[g];for(k=0;k<v;++k){if(n=F?p.c[F-1].f[k]:0)p.g[n-1]=p.c[F-1].f[k+v]||0,17>n&&(J.length=0);const Za=a.Ma[p.g[16]],$a=p.g[17]/512,ab=2**(p.g[18]-9)/A,bb=p.g[19],qa=p.g[20],cb=135.82764118168*p.g[21]/44100,db=1-p.g[22]/255,ba=1E-5*p.g[23],eb=p.g[24]/32,fb=p.g[25]/512,gb=6.283184*2**(p.g[26]-9)/A,ra=p.g[27]/255,ca=p.g[28]*A&
-2;n=(g*v+k)*A;for(m=0;4>m;++m)if(f=F?p.c[F-1].n[k+m*v]:0){if(!J[f]){var E=e=f;var x=a.Ma[p.g[0]];const hb=p.g[1],ib=p.g[3]/32,jb=a.Ma[p.g[4]],kb=p.g[5],lb=p.g[8]/32,sa=p.g[9],L=p.g[10]*p.g[10]*4,S=p.g[11]*p.g[11]*4,da=p.g[12]*p.g[12]*4,mb=1/da,nb=-p.g[13]/16;let P=p.g[14];const ob=A*2**(2-p.g[15]),ta=new Int32Array(L+S+da);let ua=0,va=0,wa=0,xa=0;for(let I=0,ea=0;I<L+S+da;I++,ea++){0<=ea&&(P=P>>8|(P&255)<<4,ea-=ob,wa=.003959503758*2**((E+(P&15)+p.g[2]-128-128)/12),xa=.003959503758*2**((E+(P&15)+
p.g[6]-128-128)/12)*(1+8E-4*p.g[7]));let G=1;I<L?G=I/L:I>=L+S&&(G=(I-L-S)*mb,G=(1-G)*3**(nb*G));ua+=wa*G**ib;let fa=x(ua)*hb;va+=xa*G**lb;fa+=jb(va)*kb;sa&&(fa+=(2*Math.random()-1)*sa);ta[I]=80*fa*G|0}J[e]=ta}E=J[f];f=0;for(e=2*n;f<E.length;f++,e+=2)q[e]+=E[f]}for(f=0;f<A;f++)m=2*(n+f),(e=q[m])||D?(D=cb,bb&&(D*=Za(ab*m)*$a+.5),D=1.5*Math.sin(D),u+=D*B,e=db*(e-B)-u,B+=D*e,e=3==qa?B:1==qa?e:u,ba&&(e*=ba,e=1>e?-1<e?a.hb(.25*e):-1:1,e/=ba),e*=eb,D=1E-5<e*e,E=Math.sin(gb*m)*fb+.5,x=e*(1-E),e*=E):x=0,m>=
ca&&(x+=q[m-ca+1]*ra,e+=q[m-ca]*ra),q[m]=x|0,q[m+1]=e|0,a.S[m]+=x|0,a.S[m+1]+=e|0}}a.wa++;if(1==a.wa/a.ka.wb){g=b.createBuffer(2,a.ja/2,44100);for(k=0;2>k;k++)for(F=g.getChannelData(k),q=k;q<a.ja;q+=2)F[q>>1]=a.S[q]/65536;return c(g)}requestAnimationFrame(d)};requestAnimationFrame(d)}
class La{constructor(){this.Ma=[this.hb,this.yb,this.xb,this.zb];this.ka=null;this.ja=this.wa=this.La=0;this.S=null}hb(a){return Math.sin(6.283184*a)}xb(a){return a%1*2-1}yb(a){return.5>a%1?1:-1}zb(a){a=a%1*4;return 2>a?a-1:3-a}getData(a,b){const c=2*Math.floor(44100*a),d=Array(b);for(let e=0;e<2*b;e+=1){const f=c+e;d[e]=0<a&&f<this.S.length?this.S[f]/32768:0}return d}}
function Ma(a){const b=a.N.sampleRate;a=a.N.createBuffer(1,.3*b,b).getChannelData(0);for(var c=0;c<a.length;c++)a[c]=2*(Math.random()-.5);c=.29-.1;for(let d=0;d<a.length;d++){let e=d/b;.01>e?a[d]*=e/.01:.11>e?a[d]*=1-(e-.01)/.1*.8:e>.3-c&&(a[d]*=(.3-e)/c)}for(c=0;c<a.length;c++)a[c]*=Math.sin(c/b*Math.PI*2*(440+100*Math.random()))}
function Na(a){const b=a.N.sampleRate;a=a.N.createBuffer(1,.5*b,b).getChannelData(0);for(var c=0;c<a.length;c++)a[c]=2*Math.random()-1;for(c=0;c<a.length;c++){let d=c/b;.05>d?a[c]*=d/.05:.25>d?a[c]*=1-(d-.05)/.2:.25<d&&(a[c]*=(.5-d)/.25)}}function Oa(a){a.K&&(a.K.stop(),a.K=null);a.Ta&&(a.K=a.N.createBufferSource(),a.K.buffer=a.Ta,a.K.connect(a.N.destination),a.K.loop=!0,a.K.start(0,a.Oa),a.startTime=a.N.currentTime-a.Oa)}
function Pa(a){a.K&&(a.Oa=a.N.currentTime-a.startTime,a.K.stop(),a.K=null)}class Qa{constructor(){this.N=new (window.AudioContext||window.webkitAudioContext);new (window.AudioContext||window.webkitAudioContext);Ma(this);Na(this);var a=new La;this.startTime=this.Oa=0;Ka(a,this.N,b=>{this.Ta=b;Oa(this)})}}function y(a){var b=K(a.width,a.height);b.h.drawImage(a,0,0);return b}
function C(a,b){for(var c=a.getContext("2d").getImageData(0,0,a.width,a.height).data,d=[],e=0;e<c.length;e+=4){var f=d,g=f.push;var k=c[e];var m=c[e+1],n=c[e+2];k=0==k+m+n+c[e+3]?null:0==k+m+n||255<k||255<m||255<n?"#000000":"#"+((k<<16)+(m<<8)+n).toString(16).padStart(6,"0");g.call(f,k)}c=[];for(e=0;e<a.height;e++)c[e]=[];f=e=0;for(g=0;g<d.length;g++)e>=a.width&&(f++,e=0),c[f][e]=d[g],b&&(c[f][e]=b(c[f][e])),e++;return c}
function H(a,b=1){let c=a.length,d=Math.max(...a.map(k=>k.length));var e=K(d*b,c*b),f=e.h;for(let k=0;k<c;k++)for(let m=0;m<d;m++){var g=a[k][m];g&&""!=g&&(f.fillStyle=g,f.fillRect(m*b,k*b,b,b))}return e}function t(a,b,c,d,e){let f=K(d,e);f.h.drawImage(a,b,c,d,e,0,0,d,e);return f}function z(a){let b=K(a.width,a.height),c=b.h;c.save();c.scale(1,-1);c.drawImage(a,0,0,a.width,-1*a.height);c.restore();return b}
function K(a=0,b=0){let c=document.createElement("canvas");c.width=a;c.height=b;c.w=a;c.i=b;c.h=c.getContext("2d");c.s={x:a/2,y:b/2};c.clear=()=>{c.h.clearRect(0,0,a,b)};c.fill=d=>{c.h.fillStyle=d;c.h.fillRect(0,0,a,b)};c.Fb=d=>{d=c.h.createPattern(d,"repeat");c.h.fillStyle=d;c.h.fillRect(0,0,a,b)};return c}function O(a,b,c=1.3,d="#000",e="sans-serif"){let f=K(b,b);var g=f.h;g.font=`${b/c}px ${e}`;g.textAlign="center";g.textBaseline="middle";g.fillStyle=d;g.fillText(a,b/2,1.1*b/2);return f}
function M(a=1,b=0){return N(a,b)|0}function N(a=1,b=0){return b+(a-b)*Math.random()}function Ra(a){var b="";for(var c=0;c<a;c++){b+="<tr>";for(var d=0;1>d;d++)b+="<td></td>";b+="</tr>"}a=document.createElement("table");a.innerHTML=b;b=[];c=a.querySelectorAll("tr");for(let e=0;e<c.length;e++)d=c[e].querySelectorAll("td"),d.forEach(f=>f.ga=g=>f.innerHTML=g),b[e]=[...d];a.bb=b;return a}
function Sa(a,b,c){var d=K(b,a),e=d.h,f=Ta(12.5*a/100,null,c);e.fillStyle=c;e.drawImage(f,0,0);e.drawImage(f,a-f.width,0);e.drawImage(f,a-f.width,b-f.height);e.drawImage(f,0,b-f.height);e.fillRect(f.width/2,1,a-f.width,b-2);e.fillRect(1,f.width/2,a-2,b-f.width);return d}
function Ta(a,b=null,c=null,d=1){var e=K(2*a+2,2*a+2),f=e.h;f.save();f.lineWidth=d;f.beginPath();f.arc(e.width/2,e.height/2,a,0,2*Math.PI,!1);null!=b&&(f.strokeStyle=b,f.stroke());null!=c&&(f.fillStyle=c,f.fill());f.restore();return e}function Q(a,b,c,d=.8,e="sans-serif"){a=a.toUpperCase();let f=K(b*a.length,b);for(let k=0;k<a.length;k++){var g=O(a[k],b,d,c,e);f.h.drawImage(g,k*b,0)}return f}
function R(a,b,c="source-atop"){let d=K(a.width,a.height),e=d.h;e.drawImage(a,0,0);e.globalCompositeOperation=c;for(c=0;c<a.width/b.width;c++)for(let f=0;f<a.height/b.height;f++)e.drawImage(b,c*b.width,f*b.height);return d}function T(a){var b=document.createElement("div");b.innerHTML=a;return b.firstChild}
function Ua(a=8,b=8){var c=K(a,b),d=c.h;d.fillStyle="#000";d.fillRect(0,0,c.width,c.height);d.fillStyle="#fff";for(let e=0;e<b;e++)for(let f=0;f<a;f++).001>Math.random()&&d.fillRect(f,e,1,1);return c}function Va(a){var b="sh1.gif?"+Math.random(),c=new Image;c.src=b;c.addEventListener("load",()=>{a(c)})}function Wa(a){a=y(a);a=C(a,b=>b);return H(a,2)}function Xa(a){var b=K(a.w,a.i);b.fill("#fff");b=R(a,b,"source-atop");a=K(a.w+2,a.i+2);a.h.drawImage(b,0,0,a.w,a.i);return a}
function Ya(a){var b=l;return parseInt(a/b)*b+b/2}function U(a,b,c){var d=b.getBoundingClientRect();c(new V({x:b.width/d.width*(a.clientX-d.left)+window.scrollX,y:b.height/d.height*(a.clientY-d.top)+window.scrollY}))}function pb(a){a=C(a);return H(a,2)}function qb(a,b,c=1){var d=a.y==b.y?0:a.y<b.y?c:-c;a.x+=a.x==b.x?0:a.x<b.x?c:-c;a.y+=d}function W(a,b){let c;c=0+Math.pow(a.x-b.x,2);c+=Math.pow(a.y-b.y,2);return c=Math.sqrt(c)}class V{constructor(a){this.x=a.x;this.y=a.y}}
function rb(a){a.layout=T("<div class='layout'></div>");a.ub=T("<div class='header'></div>");a.body=T("<div class='body'></div>");a.tb=T("<div class='footer'></div>");a.layout.appendChild(a.ub);a.layout.appendChild(a.body);a.layout.appendChild(a.tb);document.body.innerHTML="";document.body.appendChild(a.layout)}
class sb{constructor(){this.ua={ya:!1,Ib:!1,controls:!1};rb(this);var a=T("<div>Loading....</div>");this.body.append(a);this.Eb=window.innerHeight/window.innerWidth;1<this.Eb&&(l=32);this.cb=document.createElement("div");document.body.innerHTML=""}}
class tb{constructor(a){this.M=a;this.level=0;this.speed=2;this.visibility=4*l;a=this.ha=new Ia(a);this.Fa=[a.qa[0],a.qa[1]];this.ra=Ha(this.ha);this.animation={framerate:8,frame:0,Da:0,Qa:this.Fa};this.s=new V({x:3*l-l/2,y:5*l-l/2});this.Ba=new V(this.s);this.A=this.Fa[0];this.xa=!1;this.destination=new V(this.s);this.Na=[]}update(){this.animation.Qa=this.xa?this.ra:this.Fa;this.animation.frame++;this.animation.frame>=this.animation.framerate&&(this.animation.Da>=this.animation.Qa.length&&(this.animation.Da=
0),this.A=this.animation.Qa[this.animation.Da],this.animation.Da++,this.animation.frame=0);W(this.destination,this.s)>=this.speed?qb(this.s,this.destination,this.speed):(this.s=new V(this.destination),this.xa=!1);if(0==W(this.destination,this.s)&&0<this.Na.length){var a=this.Na.shift();this.destination=new V(a);this.xa=!0}}L(a){a.drawImage(this.A,this.s.x-this.A.w/2,this.s.y-this.A.i/2)}Y(a){if(!(a.y<l)){var b=Math.floor(Ya(Math.max(0,this.s.x-this.M.B.w/2)+a.x)/l);a=Math.floor(Ya(Math.max(0,this.s.y-
this.M.B.i/2)+a.y)/l);var c;if(c=0==this.xa){try{var d=1==this.M.Ha.ib[b][a]}catch(e){d=!0}c=!d}if(c){b=oa(this.M.Ha.Ab,Math.floor(this.s.x/l),Math.floor(this.s.y/l),b,a);d=[];if(1<b.length)for(c=1;c<b.length;c++)a=b[c],d.push(new V({x:a[0]*l+l/2,y:a[1]*l+l/2}));this.Na=d}}}}function ub(a){var b=a.v.pop();b=JSON.stringify(b);a.va.delete(b)}function vb(a){if(0<a.v.length)return a.v[a.v.length-1]}function wb(a){if(1<a.v.length)return a.v[a.v.length-2]}
function xb(a){a=a.v.map(b=>b.V);return 0==a.length?" ":a.join("")}class yb{constructor(){this.va=new Set;this.v=[]}length(){return this.v.length}add(a){const b=JSON.stringify(a);return this.va.has(b)?!1:(this.va.add(b),this.v.push(a),!0)}has(a){return this.va.has(JSON.stringify(a))}getAll(){return[...this.v]}}
class X{constructor(a){var b=K(a.w,a.i),c=b.h;b.fill(a.color);var d=Q(a.name,14,"#000",1.1);c.drawImage(a.A,b.w/2-a.A.w/2,b.i/2-a.A.i/2);c.drawImage(d,b.w/2-d.w/2,4);c.fillStyle=.4<a.R/a.Ia?"green":"red";c.fillRect(l/5,d.i+4,a.R/a.Ia*(b.w-l/10),4);this.x=a.x;this.y=a.y;this.oa=K(a.w+4,a.i+4);this.oa.fill(a.oa);this.canvas=b}L(a){a.drawImage(this.oa,this.x-2,this.y-2);a.drawImage(this.canvas,this.x,this.y)}}
function zb(a){var b=K(a.w,a.i),c=Da(a.w,a.i,a.w);b.h.drawImage(c,0,0);c=O("\ud83c\udf33",a.w/2,1.2);b.h.drawImage(c,-c.w/2,0);b.h.drawImage(c,a.w-c.w/2,0);a=K(b.width,b.height);a.h.globalAlpha=.5;a.h.drawImage(b,0,0);a.h.globalAlpha=1;return a}function Y(a,b,c){b=O(b,a.P,1.3);return c?R(a.Bb,b):R(a.Cb,b)}
function Ab(a,b,c,d,e,f,g=!0){if(null==b.flat().find(m=>e(m)))return b;for(let m=0;m<d;m++){const n=[];for(var k=0;k<c;k++)e(b[k][m])||n.push(b[k][m]);if(g)for(k=0;k<c;k++)b[k][m]=k>=c-n.length?n[k-(c-n.length)]:f(k,m);else for(k=0;k<c;k++)b[k][m]=k<n.length?n[k]:f(k,m)}return Ab(a,b,c,d,e,f,g)}function Bb(a,b,c){var d=a.W[M(0,a.W.length)];return{s:new V({x:a.x+b*a.u+a.u/2,y:a.y+c*a.u+a.u/2}),V:d.H,A:d.j}}
function Cb(a,b){for(let c in b)for(let d in b[c])b[c][d].s=new V({x:a.x+d*a.u+a.u/2,y:a.y+c*a.u+a.u/2}),b[c][d].r=c,b[c][d].c=d}function Db(a){a.C=new yb;var b=[];for(let d=0;d<a.rows;d++){b[d]=[];for(let e=0;e<a.cols;e++){var c=a.W[M(0,a.W.length)];b[d][e]={r:d,c:e,s:new V({x:a.x+e*a.u+a.u/2,y:a.y+d*a.u+a.u/2}),V:c.H,A:c.j}}}a.grid=b}
function Eb(a){var b=xb(a.C),c=a.P,d=a.P;if(" "==b)return g;var e={};a.W.forEach(m=>e[m.H]=m.j);var f=aa.find(m=>m.g==b);if(f){var g=K(b.length*c+2*c,d);g.fill("green");d=0;for(let m=0;m<b.length;m++){var k=b[m];e[k]&&g.h.drawImage(e[k],d,0);d+=c}f.l?(g.h.drawImage(a.Sa,d,0),d+=c,a=R(a.sb,e[f.r],"source-atop"),g.h.drawImage(a,d,0)):(g.h.drawImage(a.Sa,d,0),d+=c,g.h.drawImage(e[f.r],d,0));d+=c}else for(g=K(b.length*c,d),g.fill("red"),d=0,a=0;a<b.length;a++)k=b[a],e[k]&&g.h.drawImage(e[k],d,0),d+=c;
return g}
class Fb{constructor(a,b=()=>{}){a.body.innerHTML="";this.M=a;this.B=a.B;this.w=this.B.w;this.i=this.B.i;y(a.canvas);this.za=null;this.nb=zb(this);this.rb=b;this.u=1.85*l;this.P=.82*this.u;this.canvas=K(this.w,this.i);a.body.append(this.canvas);this.Ja=!1;this.C=new yb;this.Bb=Sa(this.P,this.P,"#fff");this.Cb=Sa(this.P,this.P,"#8c8c8c");this.Ga=O("\u2694",3*l,1.3,"#fff");this.Sa=O("\u27a1",this.P,1.3,"#fff");this.sb=O("\ud83d\udca5",this.P,1.3,"#fff");this.la=[new ka(0,1.5*l,1.5*l,O("\ud83d\udeaa",1.5*
l,1.4),()=>{b(this)}),new ka(1.5*l,1.5*l,1.5*l,O("\ud83c\udf92",1.5*l,1.4),()=>{this.Hb()})];this.Aa={name:"player",R:90,Ia:100,A:Wa(a.Ca.Ua),x:3*l,y:this.canvas.i/5,w:3*l,i:3.5*l,color:"gold",oa:"#fff"};this.ma={name:"target",R:33,Ia:100,A:O("\ud83e\udddf",64,1.3),x:this.canvas.w-3*l-3*l,y:this.canvas.i/5,w:3*l,i:3.5*l,color:"gold",oa:"#fff"};this.Va=[new X(this.Aa),new X(this.ma)];this.W=[{H:"m",e:"\ud83d\udd2e",j:Y(this,"\ud83d\udd2e",!1),U:Y(this,"\ud83d\udd2e",!0),c:"#f00"},{H:"f",e:"\ud83d\udd25",
j:Y(this,"\ud83d\udd25",!1),U:Y(this,"\ud83d\udd25",!0),c:"#f00"},{H:"w",e:"\ud83d\udca7",j:Y(this,"\ud83d\udca7",!1),U:Y(this,"\ud83d\udca7",!0),c:"#00f"},{H:"e",e:"\ud83c\udf31",j:Y(this,"\ud83c\udf31",!1),U:Y(this,"\ud83c\udf31",!0),c:"#0a0"},{H:"i",e:"\ud83c\udf2a\ufe0f",j:Y(this,"\ud83c\udf2a\ufe0f",!1),U:Y(this,"\ud83c\udf2a\ufe0f",!0),c:"#aaa"},{H:"z",e:"\u26a1",j:Y(this,"\u26a1",!1),U:Y(this,"\u26a1",!0),c:"#ff0"},{H:"l",e:"\u2600\ufe0f",j:Y(this,"\u2600\ufe0f",!1),U:Y(this,"\u2600\ufe0f",
!0),c:"#ffb"},{H:"d",e:"\ud83c\udf11",j:Y(this,"\ud83c\udf11",!1),U:Y(this,"\ud83c\udf11",!0),c:"#555"}];this.x=0;this.y=this.canvas.i/2;this.rows=Math.floor(this.canvas.i/this.u/2);this.cols=Math.floor(this.canvas.w/this.u);this.I=null;this.canvas.addEventListener("mousedown",f=>d(f));this.canvas.addEventListener("mouseup",f=>c(f));this.canvas.addEventListener("mousemove",f=>e(f));this.canvas.addEventListener("touchstart",f=>d(f));this.canvas.addEventListener("touchend",f=>c(f));this.canvas.addEventListener("touchmove",
f=>e(f));var c=f=>{this.I=null;if(0<this.C.v.length){var g=xb(this.C),k=aa.find(n=>n.g==g);if(k){if(k.m)this.C.v.forEach(n=>{this.grid[n.r][n.c].V=0}),this.grid=Ab(this,this.grid,this.rows,this.cols,n=>0==n.V,(n,q)=>Bb(this,n,q)),Cb(this,this.grid),this.ma.R-=k.l;else{var m=vb(this.C);this.C.v.forEach(n=>{this.grid[n.r][n.c].V=0});m.V=k.r;m.A=this.W.find(n=>n.H==k.r).j;this.grid=Ab(this,this.grid,this.rows,this.cols,n=>0==n.V,(n,q)=>Bb(this,n,q));Cb(this,this.grid);this.Aa.R-=5}this.Va=[new X(this.Aa),
new X(this.ma)]}}this.Ja=!1;this.C=new yb;U(f.touches?f.touches[0]:f,this.canvas,n=>{this.la.forEach(q=>{q.Y&&q.Y(n)})})},d=()=>{this.Ja=!0},e=f=>{U(f.touches?f.touches[0]:f,this.canvas,g=>{var k=new V(g);g=this.grid.flat().find(p=>W(k,p.s)<this.u/2);if(void 0!=g){var m=g.s;if(this.Ja){var n=vb(this.C),q=wb(this.C);null==n||void 0==n?this.C.add(g):null!=q&&W(m,q.s)<this.u/2?ub(this.C):W(m,n.s)<1.5*this.u&&this.C.add(g)}}})};Db(this);this.update(0)}update(a){if(0>=this.ma.R)return this.rb(this);var b=
this.canvas.h;this.canvas.fill("#000");b.drawImage(this.nb,0,0);b.fillStyle="#fff";b.fillText(Math.floor(a/1E3),10,10);b.drawImage(this.Ga,this.canvas.w/2-this.Ga.w/2,this.canvas.i/5-this.Ga.i);a=this.C.getAll();if(1<a.length){var c=Eb(this);b.drawImage(c,this.x+this.w/2-c.w/2,this.y-this.u);b.strokeStyle="#fff";b.lineWidth=this.u/6;b.beginPath();b.moveTo(a[0].s.x,a[0].s.y);for(c=1;c<a.length;c++)b.lineTo(a[c].s.x,a[c].s.y);b.stroke()}for(a=0;a<this.rows;a++)for(c=0;c<this.cols;c++){var d=this.grid[a][c],
e=!1;0!=a%2&&0!=c%2||0==a%2&&0==c%2||(e=!0);var f=this.W.find(g=>g.H==d.V);f&&(e=e?f.U:f.j,b.drawImage(e,d.s.x-e.w/2,d.s.y-e.i/2))}this.Va.forEach(g=>g.L(b));this.la.forEach(g=>g.L(this.canvas.h));requestAnimationFrame(g=>this.update(g))}}function Gb(a){a.fa=!0;a.X=!0;rb(a);a.canvas=K(a.B.w,a.B.i);a.canvas.fill("#000");Hb(a,a.canvas);a.body.append(a.canvas);Z(a)}function Hb(a,b){function c(e){d.update(e);d.L(b);requestAnimationFrame(c)}var d=new Ib(a);d.L(b);requestAnimationFrame(c)}
function Z(a){a.X=!0;null!=a.O&&a.O.remove();a.O=Object.assign(document.createElement("div"),{className:"menuDialog"});var b=[];a.fa?(b.push({ga:"<button >New Game</button>",f:"newgame"}),b.push({ga:"<button >Practice Combat</button>",f:"paracticecombat"})):b.push({ga:"<button >Resume</button>",f:"resume"});b.push({ga:`<button >Music ${a.ua.ya?"ON":"OFF"}</button>`,f:"music"});a.fa||b.push({ga:"<button >Quit</button>",f:"quit"});var c=Ra(b.length);for(let e in b){var d=T(b[e].ga);c.bb[e][0].append(d);
c.bb[e][0].onclick=()=>{Jb(a,b[e].f)}}a.O.append(c);a.body.append(a.O)}function Jb(a,b){"newgame"==b?(a.X=!1,a.fa=!1,Kb(a)):"resume"==b?(a.X=!1,a.O.remove(),a.update(a.time)):"music"==b?(a.Ea||(a.Ea=new Qa),a.ua.ya?Pa(a.Ea):Oa(a.Ea),a.ua.ya=!a.ua.ya,a.O.remove(),Z(a)):"quit"==b?(document.webkitIsFullScreen&&document.exitFullscreen(),a.X=!0,a.fa=!0,a.O.remove(),Gb(a)):"paracticecombat"==b&&(a.X=!0,a.O.remove(),new Fb(a,()=>{console.log("combat training over");a.X=!0;a.fa=!0;a.O.remove();Gb(a)}))}
function Kb(a){rb(a);a.body.innerHTML="";a.Ha=new Ga(a);a.canvas=K(a.B.w,a.B.i);a.body.innerHTML="";a.body.appendChild(a.canvas);a.body.appendChild(a.cb);a.za=new tb(a);a.la=[new ka(0,1.5*l,1.5*l,O("\ud83d\udccb",1.5*l,1.4),()=>{Z(a)})];a.v=[a.za];a.body.innerHTML="";a.body.appendChild(a.canvas);a.body.appendChild(a.cb);a.update(0);window.addEventListener("keyup",d=>{"Escape"==d.key&&Z(a)});a.I=null;a.canvas.addEventListener("mousedown",d=>b(d));a.canvas.addEventListener("mouseup",()=>{a.I=null});
a.canvas.addEventListener("mousemove",d=>c(d));a.canvas.addEventListener("touchstart",d=>b(d));a.canvas.addEventListener("touchend",()=>{a.I=null});a.canvas.addEventListener("touchmove",d=>c(d));var b=d=>{U(d.touches?d.touches[0]:d,a.canvas,e=>{a.I={x:e.x,y:e.y}})},c=d=>{a.I&&U(d.touches?d.touches[0]:d,a.canvas,e=>{a.I={x:e.x,y:e.y}})}}
class Lb extends sb{constructor(){super();this.B={w:600,i:600};Va(a=>{this.Ca=new ja(a);this.v=[];Gb(this)})}update(a){if(1!=this.X){if(1==this.fa)return this.Gb();this.v.forEach(d=>d.update(a));var b=y(this.Ha.map),c=b.h;this.v.sort((d,e)=>{let f,g;return d.Ba?null==(f=d.Ba)?void 0:f.y:Infinity-e.Ba?null==(g=e.Ba)?void 0:g.y:Infinity});this.v.forEach(d=>d.L(c));b=t(b,Math.max(0,this.za.s.x-this.B.w/2),Math.max(0,this.za.s.y-this.B.i/2),this.B.w,this.B.i);this.canvas.h.drawImage(b,0,0);this.canvas.h.fillRect;
this.la.forEach(d=>d.L(this.canvas.h));this.I&&(this.v.forEach(d=>{d.Y&&d.Y(this.I)}),this.la.forEach(d=>{d.Y&&d.Y(this.I)}),this.I=null);this.time=a;requestAnimationFrame(d=>this.update(d))}}}function Mb(a){var b="THE FAMILIAR".split(""),c=K(64*b.length,l+4),d=0;for(let g in b){var e=Q(b[g],l,"#fff",1.1,"cursive"),f=Q(b[g],l,"#b90000",1.1,"cursive");c.h.drawImage(e,d+1,1);c.h.drawImage(f,d,0);d+=l}a.F={A:c,eb:128,fb:a.Ra,ea:0}}
class Ib{constructor(a){this.M=a;this.ha=new Ia(a);this.$a=Q("BY MHMDJAWADZD",16,"#fff",1.5,"cursive");this.Wa=this.ha.qa[0];this.Xa=Xa(this.Wa);this.Xa.h.drawImage(this.Wa,1,1);this.canvas=K(a.B.w,a.B.i);pb(this.Xa);this.ra=Ha(this.ha);this.Ya=this.ra.map(c=>Xa(c));this.Ya.forEach((c,d)=>c.h.drawImage(this.ra[d],1,1));this.pb=this.Ya.map(c=>pb(c));this.lb=Ua(3*this.canvas.w,this.canvas.i);this.T=5;this.elements=[{j:O("\ud83d\udd25",32,1.3),c:"#ee4000c7",g:0,t:this.T},{j:O("\ud83d\udca7",32,1.3),
c:"#00c7eec7",g:10,t:this.T},{j:O("\ud83c\udf31",32,1.3),c:"#805a05c7",g:20,t:this.T},{j:O("\ud83c\udf2a\ufe0f",32,1.3),c:"#cdcf84c7",g:30,t:this.T},{j:O("\u26a1",32,1.3),c:"#f9ff30c7",g:40,t:this.T},{j:O("\u2600\ufe0f",32,1.3),c:"#f8ff00c7",g:50,t:this.T},{j:O("\ud83c\udf11",32,1.3),c:"#a83bf3c7",g:60,t:this.T}];this.da=Ta(4*l,"#fff",null,3);Ta(l/9,"#00f","#00f",3);a=this.canvas.i-this.da.i/2-l;var b={x:this.canvas.w/2,y:a,r:this.da.w/2};this.ta=ha(b.x,b.y,b.r);this.sa=b;this.Ra=a-this.da.i/2-l;
this.J={mb:this.pb,current:0,frames:0,framerate:16,eb:64,fb:this.Ra};Mb(this)}L(a){a.h.drawImage(this.canvas,0,0)}update(){this.canvas.h.drawImage(this.lb,0,0,M(0,this.lb.w-this.canvas.w),this.canvas.i,0,0,this.canvas.w,this.canvas.i);this.canvas.h.drawImage(this.da,this.sa.x-this.da.w/2,this.sa.y-this.da.i/2);this.canvas.h.drawImage(this.J.mb[this.J.current],this.sa.x-32,this.sa.y-32);this.J.frames++;this.J.frames>this.J.framerate&&(this.J.frames=0,this.J.current++,this.J.current>=this.J.mb.length&&
(this.J.current=0));this.canvas.h.drawImage(this.F.A,0,0,this.F.ea,this.F.A.i,this.F.eb,this.F.fb,this.F.ea,this.F.A.i);this.F.ea+=4;this.F.ea>this.F.A.w&&(this.F.ea=0);this.elements.forEach(a=>{var b=this.ta[a.g%this.ta.length];this.canvas.h.drawImage(a.j,b.x-a.j.w/2,b.y-a.j.i/2);var c=this.elements.filter(d=>d!=a)[M(this.elements.length-1)];c=this.ta[c.g%this.ta.length];this.canvas.h.save();this.canvas.h.strokeStyle=a.c;this.canvas.h.lineWidth=2;this.canvas.h.beginPath();this.canvas.h.moveTo(b.x,
b.y);this.canvas.h.lineTo(c.x,c.y);this.canvas.h.stroke();this.canvas.h.restore();a.t--;0>=a.t&&(a.t=this.T,a.g++)});this.canvas.h.drawImage(this.$a,0,this.canvas.i-this.$a.i)}}document.addEventListener("DOMContentLoaded",function(){window.M=new Lb},!1);
