let k=32,da=10;
var q={Fb:[{g:[0,0,140,0,0,0,140,0,0,255,158,158,158,0,0,0,0,51,2,1,2,58,239,0,32,88,1,157,2],p:[1,1,1,1],c:[{n:[161,,,,,,,,,,,,,,,,163,,,,,,,,159],f:[]}]},{g:[0,91,128,0,0,95,128,12,0,0,12,0,72,0,0,0,0,0,0,0,2,255,0,0,32,83,3,130,4],p:[1,1,2,1],c:[{n:[144,,151,,149,,147,,146,,147,,146,,144,,144,,151,,149,,147,,146,,147,,146,,144],f:[]},{n:[156,,163,,161,,159,,158,,159,,158,,156,,156,,163,,161,,159,,158,,159,,158,,168],f:[]}]},{g:[0,16,133,0,0,28,126,12,0,0,2,0,60,0,0,0,0,0,0,0,2,91,0,0,32,47,3,157,
2],p:[1,2,1,2],c:[{n:[144,,151,,149,,147,,146,,147,,146,,144,,144,,151,,149,,147,,146,,147,,146,,144],f:[]},{n:[168,,175,,173,,171,,170,,171,,170,,168,,168,,175,,173,,171,,170,,171,,170,,168],f:[]}]},{g:[0,255,116,79,0,255,116,0,83,0,4,6,69,52,0,0,0,0,0,0,2,14,0,0,32,0,0,0,0],p:[1,1,1,1],c:[{n:[144,,151,,149,,147,,146,,147,,146,,144,,144,,151,,149,,147,,146,,147,,146,,144,,,159,,,,159,,,,159,,,,,,,,,,,,159,,159],f:[]}]}],mb:8269,lb:32,rb:3,xb:4},ea=[{g:"mmmmmm",r:"m",l:!0,j:100,o:0},{g:"mmmmm",r:"m",
l:!0,j:40,o:0},{g:"mmmm",r:"m",l:!0,j:15,o:0},{g:"mmm",r:"m",l:!0,j:5,o:0},{g:"mm",r:"m",l:!0,j:3,o:0},{g:"ff",r:"m",l:!1,j:0,o:0},{g:"ww",r:"m",l:!1,j:0,o:0},{g:"ee",r:"m",l:!1,j:0,o:0},{g:"ii",r:"m",l:!1,j:0,o:0},{g:"zz",r:"m",l:!1,j:0,o:0},{g:"ll",r:"m",l:!1,j:0,o:0},{g:"dd",r:"m",l:!1,j:0,o:0},{g:"mf",r:"f",l:!0,j:3,o:0},{g:"mw",r:"w",l:!0,j:3,o:0},{g:"me",r:"e",l:!0,j:3,o:0},{g:"mi",r:"i",l:!0,j:3,o:0},{g:"mz",r:"z",l:!0,j:3,o:0},{g:"ml",r:"l",l:!0,j:3,o:0},{g:"md",r:"d",l:!0,j:3,o:0},{g:"mff",
r:"f",l:!0,j:7,o:0},{g:"mww",r:"w",l:!0,j:7,o:0},{g:"mee",r:"e",l:!0,j:7,o:0},{g:"mii",r:"i",l:!0,j:7,o:0},{g:"mzz",r:"z",l:!0,j:7,o:0},{g:"mll",r:"l",l:!0,j:7,o:0},{g:"mdd",r:"ld",l:!0,j:7,o:0},{g:"mfff",r:"f",l:!0,j:15,o:0},{g:"mwww",r:"w",l:!0,j:15,o:0},{g:"meee",r:"e",l:!0,j:15,o:0},{g:"miii",r:"i",l:!0,j:15,o:0},{g:"mzzz",r:"z",l:!0,j:15,o:0},{g:"mlll",r:"l",l:!0,j:15,o:0},{g:"mddd",r:"d",l:!0,j:15,o:0},{g:"mfi",r:"f",l:!0,j:8,o:0},{g:"mfe",r:"f",l:!0,j:8,o:0},{g:"mwi",r:"w",l:!0,j:8,o:0},{g:"mwe",
r:"w",l:!0,j:8,o:0}];function fa(a,b,c){const d=[];for(let e=0;70>e;e++){const f=2*Math.PI*e/70;d.push({x:a+c*Math.cos(f),y:b+c*Math.sin(f)})}return d}class r{constructor(a,b,c,d,e,f){this.x=a;this.y=b;this.w=c;this.i=d;this.v=e;this.onclick=f}P(a){var b=a.x;a=a.y;if(b>=this.x&&b<=this.x+this.w&&a>=this.y&&a<=this.y+this.i){if(this.onclick)this.onclick(this);return!0}return!1}L(a){a.drawImage(this.v,this.x,this.y,this.w,this.i)}update(){}}
function ha(a,b){let c=a[0],d=b[c[0]][c[1]];for(const e of a){const [f,g]=e;b[f][g]<d&&(c=e,d=b[f][g])}return c}function ia(a,b){const c=[b];for(;a.hasOwnProperty(`${b[0]}-${b[1]}`);)b=a[`${b[0]}-${b[1]}`],c.unshift(b);return c}function ja(a,b,c){const d=[];0<b&&d.push([b-1,c]);b<a.rows-1&&d.push([b+1,c]);0<c&&d.push([b,c-1]);c<a.cols-1&&d.push([b,c+1]);return d}
function ka(a,b,c,d,e){b=Math.floor(b);c=Math.floor(c);d=Math.floor(d);e=Math.floor(e);const f=[],g=new Set,h={},l=Array(a.rows).fill(null).map(()=>Array(a.cols).fill(Infinity));l[b][c]=0;const m=Array(a.rows).fill(null).map(()=>Array(a.cols).fill(Infinity));m[b][c]=Math.abs(b-d)+Math.abs(c-e);for(f.push([b,c]);0<f.length;){b=ha(f,m);const [p,n]=b;if(p===d&&n===e)return ia(h,b);f.splice(f.indexOf(b),1);g.add(`${p}-${n}`);c=ja(a,p,n);for(const y of c){const [u,t]=y;g.has(`${u}-${t}`)||a.wb[u][t]||
(c=l[p][n]+1,c<l[u][t]&&(h[`${u}-${t}`]=b,l[u][t]=c,m[u][t]=c+(Math.abs(u-d)+Math.abs(t-e)),f.includes(y)||f.push(y)))}}return null}class la{constructor(a){this.wb=a;this.rows=a.length;this.cols=a[0].length}}class ma{constructor(a,b){this.F=a;this.Xa=w(b,c=>""==c?null:c);this.Ja=[{c:"#847e87",G:0,J:"",m:void 0}]}}
class na{constructor(a,b){this.F=a;this.U=[x("\ud83c\udf00",2*k,1.3),x("\ud83c\udf00",2*k,1),x("\ud83c\udf00",2*k,1.1),x("\ud83c\udf00",2*k,1.2)];this.animate={framerate:10,frame:0,index:0};a=(b.g+b.eb)/2;this.level=8>a?1:16>a?2:24>a?3:32>a?4:40>a?5:48>a?6:56>a?7:64>a?8:9+Math.round(Math.random());this.v=this.U[0];this.s=new A({x:b.g*k+this.v.w/2,y:b.eb*k+this.v.i/2})}update(){this.animate.frame++;this.animate.frame>this.animate.framerate&&(this.v=this.U[this.animate.index],this.animate.frame=0,this.animate.index=
this.animate.index>=this.U.length-1?0:this.animate.index+1)}L(a){a.drawImage(this.v,this.s.x-this.v.w/2,this.s.y-this.v.i/2);a.fillStyle="blue";a.fillRect(this.s.x,this.s.y,2,2)}P(a){E(this.s,a)<2*k&&(console.log("click near me",this),oa(this.F,this))}}function pa(a,b){var c=qa(64*k,64*k,k*k),d={};a.Ja.map(f=>d[f.c]=f.m);a=w(b,f=>""==f?null:f);b=G(64*k,64*k);var e=b.h;e.drawImage(c,0,0);for(let f=0;64>f;f++)for(let g=0;64>g;g++)c=d[a[g][f]],void 0!=c&&e.drawImage(c,f*k,g*k);return b}
class za extends ma{constructor(a){super(a,a.Fa.ib);this.ch=this.F.C.i;var b=Aa(k,k),c=Ba(k,k),d=Ca(k,k),e=x("\ud83c\udf33",k,1.3),f=x("\ud83c\udfe1",2*k,1.3),g=x("\ud83c\udfe0",2*k,1.3),h=x("\u26ea",3*k,1.3),l=x("\ud83c\udfeb",3*k,1.3),m=x("\u26fa",3*k,1.3);x("\ud83c\udf00",2*k,1.3);var p=Da(k);this.hb=[];this.Ja=[{c:"#99e550",G:0,J:"",m:void 0},{c:"#639bff",G:1,J:"",m:d},{c:"#6abe30",G:1,J:"",m:e},{c:"#76428a",G:1,J:"house1",m:f},{c:"#d77bba",G:1,J:"house2",m:g},{c:"#d9a066",G:0,J:"",m:b},{c:"#767676",
G:1,J:"",m:p},{c:"#8f974a",G:1,J:"church",m:h},{c:"#fbf236",G:1,J:"townhall",m:l},{c:"#663931",G:0,J:"",m:c},{c:"#524b24",G:1,J:"tent",m},{c:"#222034",G:1,J:"portal",m:void 0}];for(b=0;64>b;b++)for(c=0;64>c;c++)"#222034"==this.Xa[c][b]&&this.hb.push({g:b,eb:c});this.map=pa(this,a.Fa.ib);a=this.Xa;c=this.Ja;b={};for(var n in c)b[c[n].c]=c[n].G;n=[];for(c=0;c<a.length;c++)for(n[c]=[],d=0;d<a[c].length;d++)e=b[a[d][c]],n[c][d]=void 0!=e&&0==e?0:1;this.kb=n;this.Bb=new la(this.kb)}}
function Ea(a){var b=[];for(let c=2;5>=c;c++)b.push(a.U[c]);return b}class Fa{constructor(a){this.U=Ga(a.Fa)}}function Ha(a){a.oa=q;a.Na=q.rb;a.Aa=0;a.na=q.mb*q.lb*(a.Na+1)*2;a.W=new Int32Array(a.na)}
function Ia(a,b,c){Ha(a);var d=()=>{var e,f,g,h,l,m,p=new Int32Array(a.na);const n=a.oa.Fb[a.Aa],y=a.oa.mb,u=a.oa.lb;let t=0,z=0;var B=!1;const M=[];for(g=0;g<=a.Na;++g){var D=n.p[g];for(h=0;h<u;++h){if(m=D?n.c[D-1].f[h]:0)n.g[m-1]=n.c[D-1].f[h+u]||0,17>m&&(M.length=0);const ab=a.Oa[n.g[16]],bb=n.g[17]/512,cb=2**(n.g[18]-9)/y,db=n.g[19],ra=n.g[20],eb=135.82764118168*n.g[21]/44100,fb=1-n.g[22]/255,Y=1E-5*n.g[23],gb=n.g[24]/32,hb=n.g[25]/512,ib=6.283184*2**(n.g[26]-9)/y,sa=n.g[27]/255,Z=n.g[28]*y&-2;
m=(g*u+h)*y;for(l=0;4>l;++l)if(f=D?n.c[D-1].n[h+l*u]:0){if(!M[f]){var C=e=f;var v=a.Oa[n.g[0]];const jb=n.g[1],kb=n.g[3]/32,lb=a.Oa[n.g[4]],mb=n.g[5],nb=n.g[8]/32,ta=n.g[9],N=n.g[10]*n.g[10]*4,T=n.g[11]*n.g[11]*4,aa=n.g[12]*n.g[12]*4,ob=1/aa,pb=-n.g[13]/16;let R=n.g[14];const qb=y*2**(2-n.g[15]),ua=new Int32Array(N+T+aa);let va=0,wa=0,xa=0,ya=0;for(let H=0,ba=0;H<N+T+aa;H++,ba++){0<=ba&&(R=R>>8|(R&255)<<4,ba-=qb,xa=.003959503758*2**((C+(R&15)+n.g[2]-128-128)/12),ya=.003959503758*2**((C+(R&15)+n.g[6]-
128-128)/12)*(1+8E-4*n.g[7]));let F=1;H<N?F=H/N:H>=N+T&&(F=(H-N-T)*ob,F=(1-F)*3**(pb*F));va+=xa*F**kb;let ca=v(va)*jb;wa+=ya*F**nb;ca+=lb(wa)*mb;ta&&(ca+=(2*Math.random()-1)*ta);ua[H]=80*ca*F|0}M[e]=ua}C=M[f];f=0;for(e=2*m;f<C.length;f++,e+=2)p[e]+=C[f]}for(f=0;f<y;f++)l=2*(m+f),(e=p[l])||B?(B=eb,db&&(B*=ab(cb*l)*bb+.5),B=1.5*Math.sin(B),t+=B*z,e=fb*(e-z)-t,z+=B*e,e=3==ra?z:1==ra?e:t,Y&&(e*=Y,e=1>e?-1<e?a.jb(.25*e):-1:1,e/=Y),e*=gb,B=1E-5<e*e,C=Math.sin(ib*l)*hb+.5,v=e*(1-C),e*=C):v=0,l>=Z&&(v+=p[l-
Z+1]*sa,e+=p[l-Z]*sa),p[l]=v|0,p[l+1]=e|0,a.W[l]+=v|0,a.W[l+1]+=e|0}}a.Aa++;if(1==a.Aa/a.oa.xb){g=b.createBuffer(2,a.na/2,44100);for(h=0;2>h;h++)for(D=g.getChannelData(h),p=h;p<a.na;p+=2)D[p>>1]=a.W[p]/65536;return c(g)}requestAnimationFrame(d)};requestAnimationFrame(d)}
class Ja{constructor(){this.Oa=[this.jb,this.zb,this.yb,this.Ab];this.oa=null;this.na=this.Aa=this.Na=0;this.W=null}jb(a){return Math.sin(6.283184*a)}yb(a){return a%1*2-1}zb(a){return.5>a%1?1:-1}Ab(a){a=a%1*4;return 2>a?a-1:3-a}getData(a,b){const c=2*Math.floor(44100*a),d=Array(b);for(let e=0;e<2*b;e+=1){const f=c+e;d[e]=0<a&&f<this.W.length?this.W[f]/32768:0}return d}}
function Ka(a){const b=a.R.sampleRate;a=a.R.createBuffer(1,.3*b,b).getChannelData(0);for(var c=0;c<a.length;c++)a[c]=2*(Math.random()-.5);c=.29-.1;for(let d=0;d<a.length;d++){let e=d/b;.01>e?a[d]*=e/.01:.11>e?a[d]*=1-(e-.01)/.1*.8:e>.3-c&&(a[d]*=(.3-e)/c)}for(c=0;c<a.length;c++)a[c]*=Math.sin(c/b*Math.PI*2*(440+100*Math.random()))}
function La(a){const b=a.R.sampleRate;a=a.R.createBuffer(1,.5*b,b).getChannelData(0);for(var c=0;c<a.length;c++)a[c]=2*Math.random()-1;for(c=0;c<a.length;c++){let d=c/b;.05>d?a[c]*=d/.05:.25>d?a[c]*=1-(d-.05)/.2:.25<d&&(a[c]*=(.5-d)/.25)}}function Ma(a){a.O&&(a.O.stop(),a.O=null);a.Va&&(a.O=a.R.createBufferSource(),a.O.buffer=a.Va,a.O.connect(a.R.destination),a.O.loop=!0,a.O.start(0,a.Qa),a.startTime=a.R.currentTime-a.Qa)}
function Na(a){a.O&&(a.Qa=a.R.currentTime-a.startTime,a.O.stop(),a.O=null)}class Oa{constructor(){this.R=new (window.AudioContext||window.webkitAudioContext);new (window.AudioContext||window.webkitAudioContext);Ka(this);La(this);var a=new Ja;this.startTime=this.Qa=0;Ia(a,this.R,b=>{this.Va=b;Ma(this)})}}
function w(a,b){for(var c=a.getContext("2d").getImageData(0,0,a.width,a.height).data,d=[],e=0;e<c.length;e+=4){var f=d,g=f.push;var h=c[e];var l=c[e+1],m=c[e+2];h=0==h+l+m+c[e+3]?null:0==h+l+m||255<h||255<l||255<m?"#000000":"#"+((h<<16)+(l<<8)+m).toString(16).padStart(6,"0");g.call(f,h)}c=[];for(e=0;e<a.height;e++)c[e]=[];f=e=0;for(g=0;g<d.length;g++)e>=a.width&&(f++,e=0),c[f][e]=d[g],b&&(c[f][e]=b(c[f][e])),e++;return c}function I(a){var b=G(a.width,a.height);b.h.drawImage(a,0,0);return b}
function x(a,b,c=1.3,d="#000",e="sans-serif"){let f=G(b,b);var g=f.h;g.font=`${b/c}px ${e}`;g.textAlign="center";g.textBaseline="middle";g.fillStyle=d;g.fillText(a,b/2,1.1*b/2);return f}function G(a=0,b=0){let c=document.createElement("canvas");c.width=a;c.height=b;c.w=a;c.i=b;c.h=c.getContext("2d");c.s={x:a/2,y:b/2};c.clear=()=>{c.h.clearRect(0,0,a,b)};c.fill=d=>{c.h.fillStyle=d;c.h.fillRect(0,0,a,b)};c.Hb=d=>{d=c.h.createPattern(d,"repeat");c.h.fillStyle=d;c.h.fillRect(0,0,a,b)};return c}
function Pa(a){var b="";for(var c=0;c<a;c++){b+="<tr>";for(var d=0;1>d;d++)b+="<td></td>";b+="</tr>"}a=document.createElement("table");a.innerHTML=b;b=[];c=a.querySelectorAll("tr");for(let e=0;e<c.length;e++)d=c[e].querySelectorAll("td"),d.forEach(f=>f.aa=g=>f.innerHTML=g),b[e]=[...d];a.ia=b;return a}
function Qa(a,b,c){var d=G(b,a),e=d.h,f=Ra(12.5*a/100,null,c);e.fillStyle=c;e.drawImage(f,0,0);e.drawImage(f,a-f.width,0);e.drawImage(f,a-f.width,b-f.height);e.drawImage(f,0,b-f.height);e.fillRect(f.width/2,1,a-f.width,b-2);e.fillRect(1,f.width/2,a-2,b-f.width);return d}
function Ra(a,b=null,c=null,d=1){var e=G(2*a+2,2*a+2),f=e.h;f.save();f.lineWidth=d;f.beginPath();f.arc(e.width/2,e.height/2,a,0,2*Math.PI,!1);null!=b&&(f.strokeStyle=b,f.stroke());null!=c&&(f.fillStyle=c,f.fill());f.restore();return e}function J(a,b,c,d=.8,e="sans-serif"){a=a.toUpperCase();let f=G(b*a.length,b);for(let h=0;h<a.length;h++){var g=x(a[h],b,d,c,e);f.h.drawImage(g,h*b,0)}return f}
function K(a,b){b=J(a,16,b,1,"cursive");a=J(a,16,"#fff",1,"cursive");var c=G(b.w+4,b.w+4);c.h.drawImage(a,1,1);c.h.drawImage(b,0,0);return c}function L(a,b,c="source-atop"){if(!a||!b)return a;let d=G(a.width,a.height),e=d.h;e.drawImage(a,0,0);e.globalCompositeOperation=c;for(c=0;c<a.width/b.width;c++)for(let f=0;f<a.height/b.height;f++)e.drawImage(b,c*b.width,f*b.height);return d}
function Sa(a){let b=G(a.width,a.height),c=b.h;c.save();c.scale(1,-1);c.drawImage(a,0,0,a.width,-1*a.height);c.restore();return b}function O(a){var b=document.createElement("div");b.innerHTML=a;return b.firstChild}function Ta(a=8,b=8){var c=G(a,b),d=c.h;d.fillStyle="#000";d.fillRect(0,0,c.width,c.height);d.fillStyle="#fff";for(let e=0;e<b;e++)for(let f=0;f<a;f++).001>Math.random()&&d.fillRect(f,e,1,1);return c}
function Ua(a){var b="sh1.gif?"+Math.random(),c=new Image;c.src=b;c.addEventListener("load",()=>{a(c)})}function Va(a,b=1){let c=a.length,d=Math.max(...a.map(h=>h.length));var e=G(d*b,c*b),f=e.h;for(let h=0;h<c;h++)for(let l=0;l<d;l++){var g=a[h][l];g&&""!=g&&(f.fillStyle=g,f.fillRect(l*b,h*b,b,b))}return e}function Wa(a){a=I(a);a=w(a,b=>b);return Va(a,2)}function P(a,b,c,d,e){let f=G(d,e);f.h.drawImage(a,b,c,d,e,0,0,d,e);return f}
function Xa(a){var b=G(a.w,a.i);b.fill("#fff");b=L(a,b,"source-atop");a=G(a.w+2,a.i+2);a.h.drawImage(b,0,0,a.w,a.i);return a}function Ya(a){var b=k;return parseInt(a/b)*b+b/2}
function Za(a,b,c,d){a=G(a,b);a.h.fillStyle=d;a.h.fillRect(c.w/2,c.i/2,a.w-c.w,a.i-c.i);d=G(a.w,c.i);b=G(c.w,a.i);for(var e=0;e<a.w-c.w;)d.h.drawImage(c,e,0),e+=c.w/2;for(e=0;e<a.i-c.i;)b.h.drawImage(c,0,e),e+=c.i/2;a.h.drawImage(d,0,-2);a.h.drawImage(d,0,a.i-d.i+2);a.h.drawImage(b,-1,0);a.h.drawImage(b,a.w-b.w+1,0);return a}function Q(a,b,c){var d=b.getBoundingClientRect();c(new A({x:b.width/d.width*(a.clientX-d.left)+window.scrollX,y:b.height/d.height*(a.clientY-d.top)+window.scrollY}))}
function $a(a){a=w(a);return Va(a,2)}function S(a=1,b=0){return b+(a-b)*Math.random()}function U(a=1,b=0){return S(a,b)|0}function Aa(a=64,b=64){const c=G(a,b),d=c.h;d.fillStyle="#a67c52";d.fillRect(0,0,a,b);for(let e=0;e<a+b;e++){const f=U(0,a),g=U(0,b),h=U(2,5);d.globalAlpha=S(.15,.35);d.fillStyle=.5<S()?"#c2b280":"#7c5c36";d.beginPath();d.arc(f,g,h,0,2*Math.PI);d.fill()}d.globalAlpha=1;return c}
function Ba(a=64,b=64){const c=G(a,b),d=c.h;d.fillStyle="#b0a99f";d.fillRect(0,0,a,b);const e=a/4;b/=4;for(let f=0;4>f;f++)for(let g=0;4>g;g++){let h=g*e+(1===f%2?e/2:0);if(h+e>a)continue;let l=f*b;d.fillStyle=.5<S()?"#d6d2c4":"#a59e91";d.fillRect(h,l,e-2,b-2);d.strokeStyle="#8d867a";d.lineWidth=1;d.strokeRect(h,l,e-2,b-2)}d.globalAlpha=1;return c}
function Ca(a=64,b=64){const c=G(a,b),d=c.h;d.fillStyle="#639bff";d.fillRect(0,0,a,b);for(let e=0;e<a+b;e++){const f=U(0,a),g=U(0,b),h=U(2,6);d.globalAlpha=S(.15,.35);d.fillStyle="#a3d8ff";d.beginPath();d.arc(f,g,h,0,2*Math.PI);d.fill()}d.globalAlpha=1;return c}
function Da(a=64){const b=document.createElement("canvas");b.width=b.height=a;const c=b.getContext("2d");c.fillStyle="#e6d3b3";c.fillRect(0,0,a,a);const d=["#d1bfa3","#c2ad8f","#b8a07d","#e0ceb0"],e=a/4*.9,f=a/3*.7;for(let g=0;3>g;g++)for(let h=0;4>h;h++){let l=h*a/4+g%2*a/8,m=g*a/3;c.beginPath();c.ellipse(l+e/2,m+f/2,e/2,f/2,0,0,2*Math.PI);c.fillStyle=d[Math.floor(Math.random()*d.length)];c.shadowColor="#bba98a";c.shadowBlur=4;c.fill();c.shadowBlur=0}c.globalAlpha=.08;c.fillStyle="#fff";c.beginPath();
c.arc(.7*a,.3*a,.25*a,0,2*Math.PI);c.fill();c.globalAlpha=1;return b}function qa(a=64,b=64,c=8){var d=[x("\ud83c\udf39",12,1.3),x("\ud83c\udf37",12,1.3),x("\ud83c\udf3b",12,1.3),x("\ud83c\udf3c",12,1.3),x("\ud83c\udf31",12,1.3)];const e=G(a,b);var f=e.h,g=rb(a,b);f.fillStyle="#4caf50";f.drawImage(g,0,0);for(g=0;g<c;g++)f.drawImage(d[U(0,d.length)],U(0,a-12),U(0,b-12));return e}
function rb(a=64,b=64){const c=G(a,b),d=c.h;d.fillStyle="#4caf50";d.fillRect(0,0,a,b);for(let e=0;e<a+b;e++){const f=U(0,a),g=U(0,b),h=U(2,5);d.globalAlpha=S(.18,.38);d.fillStyle=.5<S()?"#81c784":"#388e3c";d.beginPath();d.arc(f,g,h,0,2*Math.PI);d.fill()}d.globalAlpha=1;return c}
function Ga(a){function b(z){return P(d,z[0],z[1],z[2],z[3])}function c(z,B,M,D,C){var v=I(d);v.h.drawImage(h,e.Ma[0],e.Ma[1]+(z?-2:0));v.h.drawImage(l,e.Ra[0],e.Ra[1]+(B?-2:0));M?v.h.drawImage(g,e.sa[0],e.sa[1]+4):v.h.drawImage(f,e.sa[0],e.sa[1]);D?v.h.drawImage(p,e.ma[0],e.ma[1]-4):v.h.drawImage(m,e.ma[0],e.ma[1]);C?v.h.drawImage(y,e.qa[0],e.qa[1]-4):v.h.drawImage(n,e.qa[0],e.qa[1]);return v}var d=I(a.Wa);a=[];var e={sa:[27,20,4,6],Ma:[7,29,8,3],Ra:[17,29,8,3],ma:[5,15,5,7],qa:[22,15,5,7]},f=b(e.sa),
g=Sa(f),h=b(e.Ma),l=b(e.Ra),m=b(e.ma),p=Sa(m),n=b(e.qa),y=Sa(n);for(var u in e){var t=e[u];d.h.clearRect(t[0],t[1],t[2],t[3])}u=[{ca:0,ea:0,fa:0,ba:0,da:0},{ca:0,ea:0,fa:0,ba:0,da:0},{ca:1,ea:0,fa:0,ba:0,da:1},{ca:1,ea:0,fa:1,ba:0,da:0},{ca:0,ea:1,fa:0,ba:1,da:0},{ca:0,ea:1,fa:1,ba:0,da:0}];for(let z in u)t=u[z],t=c(t.ca,t.ea,t.fa,t.ba,t.da),a.push(t);return a}
class sb{constructor(a){a=I(a);a=w(a,b=>""==b||"#fff"==b||"#ffffff"==b?null:b);a=Va(a,1);this.Wa=P(a,0,0,32,32);P(a,32,0,32,32);this.ib=P(a,0,32,64,64);P(a,0,80,16,16)}}function E(a,b){let c;c=0+Math.pow(a.x-b.x,2);c+=Math.pow(a.y-b.y,2);return c=Math.sqrt(c)}function tb(a,b,c=1){var d=a.y==b.y?0:a.y<b.y?c:-c;a.x+=a.x==b.x?0:a.x<b.x?c:-c;a.y+=d}class A{constructor(a){this.x=a.x;this.y=a.y}}
function ub(a){a.layout=O("<div class='layout'></div>");a.vb=O("<div class='header'></div>");a.body=O("<div class='body'></div>");a.ub=O("<div class='footer'></div>");a.layout.appendChild(a.vb);a.layout.appendChild(a.body);a.layout.appendChild(a.ub);document.body.innerHTML="";document.body.appendChild(a.layout)}
class vb{constructor(){this.wa={Ca:!1,Jb:!1,controls:!1};ub(this);var a=O("<div>Loading....</div>");this.body.append(a);this.Gb=window.innerHeight/window.innerWidth;1<this.Gb&&(k=32);da=Math.floor(window.innerWidth/k)-1;this.cb=document.createElement("div");document.body.innerHTML=""}}
class wb{constructor(a){this.F=a;this.level=0;this.speed=2;this.visibility=4*k;a=this.la=new Fa(a);this.Ia=[a.U[0],a.U[1]];this.ta=Ea(this.la);this.animation={framerate:8,frame:0,Ga:0,Sa:this.Ia};this.s=new A({x:3*k-k/2,y:5*k-k/2});this.Ea=new A(this.s);this.v=this.Ia[0];this.Ba=!1;this.destination=new A(this.s);this.Pa=[]}update(){this.animation.Sa=this.Ba?this.ta:this.Ia;this.animation.frame++;this.animation.frame>=this.animation.framerate&&(this.animation.Ga>=this.animation.Sa.length&&(this.animation.Ga=
0),this.v=this.animation.Sa[this.animation.Ga],this.animation.Ga++,this.animation.frame=0);E(this.destination,this.s)>=this.speed?tb(this.s,this.destination,this.speed):(this.s=new A(this.destination),this.Ba=!1);if(0==E(this.destination,this.s)&&0<this.Pa.length){var a=this.Pa.shift();this.destination=new A(a);this.Ba=!0}}L(a){a.drawImage(this.v,this.s.x-this.v.w/2,this.s.y-this.v.i/2)}P(a){if(!(a.y<k)){var b=Math.floor(Ya(Math.max(0,this.s.x-this.F.C.w/2)+a.x)/k);a=Math.floor(Ya(Math.max(0,this.s.y-
this.F.C.i/2)+a.y)/k);var c;if(c=0==this.Ba){try{var d=1==this.F.ya.kb[b][a]}catch(e){d=!0}c=!d}if(c){b=ka(this.F.ya.Bb,Math.floor(this.s.x/k),Math.floor(this.s.y/k),b,a);d=[];if(1<b.length)for(c=1;c<b.length;c++)a=b[c],d.push(new A({x:a[0]*k+k/2,y:a[1]*k+k/2}));this.Pa=d}}}}function xb(a){var b=a.B.pop();b=JSON.stringify(b);a.xa.delete(b)}function yb(a){if(0<a.B.length)return a.B[a.B.length-1]}function zb(a){if(1<a.B.length)return a.B[a.B.length-2]}
function Ab(a){a=a.B.map(b=>b.Z);return 0==a.length?" ":a.join("")}class Bb{constructor(){this.xa=new Set;this.B=[]}length(){return this.B.length}add(a){const b=JSON.stringify(a);return this.xa.has(b)?!1:(this.xa.add(b),this.B.push(a),!0)}has(a){return this.xa.has(JSON.stringify(a))}getAll(){return[...this.B]}}
class V{constructor(a){var b=G(a.w,a.i),c=b.h;b.fill(a.color);var d=J(a.name,14,"#000",1.1);c.drawImage(a.v,b.w/2-a.v.w/2,b.i/2-a.v.i/2);c.drawImage(d,b.w/2-d.w/2,4);c.fillStyle=.4<a.V/a.La?"green":"red";c.fillRect(k/5,d.i+4,a.V/a.La*(b.w-k/10),4);this.x=a.x;this.y=a.y;this.ra=G(a.w+4,a.i+4);this.ra.fill(a.ra);this.canvas=b}L(a){a.drawImage(this.ra,this.x-2,this.y-2);a.drawImage(this.canvas,this.x,this.y)}}
function Cb(a){var b=G(a.w,a.i),c=qa(a.w,a.i,a.w);b.h.drawImage(c,0,0);c=x("\ud83c\udf33",a.w/2,1.2);b.h.drawImage(c,-c.w/2,0);b.h.drawImage(c,a.w-c.w/2,0);a=G(b.width,b.height);a.h.globalAlpha=.5;a.h.drawImage(b,0,0);a.h.globalAlpha=1;return a}function W(a,b,c){b=x(b,a.T,1.3);return c?L(a.Db,b):L(a.Eb,b)}
function Db(a,b,c,d,e,f,g=!0){if(null==b.flat().find(l=>e(l)))return b;for(let l=0;l<d;l++){const m=[];for(var h=0;h<c;h++)e(b[h][l])||m.push(b[h][l]);if(g)for(h=0;h<c;h++)b[h][l]=h>=c-m.length?m[h-(c-m.length)]:f(h,l);else for(h=0;h<c;h++)b[h][l]=h<m.length?m[h]:f(h,l)}return Db(a,b,c,d,e,f,g)}function Eb(a,b,c){var d=a.$[U(0,a.$.length)];return{s:new A({x:a.x+b*a.A+a.A/2,y:a.y+c*a.A+a.A/2}),Z:d.K,v:d.m}}
function Fb(a,b){for(let c in b)for(let d in b[c])b[c][d].s=new A({x:a.x+d*a.A+a.A/2,y:a.y+c*a.A+a.A/2}),b[c][d].r=c,b[c][d].c=d}function Gb(a){a.D=new Bb;var b=[];for(let d=0;d<a.rows;d++){b[d]=[];for(let e=0;e<a.cols;e++){var c=a.$[U(0,a.$.length)];b[d][e]={r:d,c:e,s:new A({x:a.x+e*a.A+a.A/2,y:a.y+d*a.A+a.A/2}),Z:c.K,v:c.m}}}a.grid=b}
function Hb(a){var b=Ab(a.D),c=a.T,d=a.T;if(" "==b)return g;var e={};a.$.forEach(l=>e[l.K]=l.m);var f=ea.find(l=>l.g==b);if(f){var g=G(b.length*c+2*c,d);g.fill("green");d=0;for(let l=0;l<b.length;l++){var h=b[l];e[h]&&g.h.drawImage(e[h],d,0);d+=c}f.j?(g.h.drawImage(a.Ua,d,0),d+=c,a=L(a.tb,e[f.r],"source-atop"),g.h.drawImage(a,d,0)):(g.h.drawImage(a.Ua,d,0),d+=c,g.h.drawImage(e[f.r],d,0));d+=c}else for(g=G(b.length*c,d),g.fill("red"),d=0,a=0;a<b.length;a++)h=b[a],e[h]&&g.h.drawImage(e[h],d,0),d+=c;
return g}
class Ib{constructor(a,b=()=>{}){a.body.innerHTML="";this.F=a;this.C=a.C;this.w=this.C.w;this.i=this.C.i;I(a.canvas);this.ka=null;this.pb=Cb(this);this.sb=b;this.A=1.85*k;this.T=.82*this.A;this.canvas=G(this.w,this.i);a.body.append(this.canvas);this.za=!1;this.D=new Bb;this.Db=Qa(this.T,this.T,"#fff");this.Eb=Qa(this.T,this.T,"#8c8c8c");this.Ka=x("\u2694",3*k,1.3,"#fff");this.Ua=x("\u27a1",this.T,1.3,"#fff");this.tb=x("\ud83d\udca5",this.T,1.3,"#fff");this.S=[new r(0,0,1.5*k,1.5*k,x("\ud83d\udeaa",1.5*
k,1.4),()=>{b(this)})];this.Da={name:"player",V:90,La:100,v:Wa(a.Fa.Wa),x:3*k,y:this.canvas.i/5,w:3*k,i:3.5*k,color:"gold",ra:"#fff"};this.pa={name:"target",V:33,La:100,v:x("\ud83e\udddf",64,1.3),x:this.canvas.w-3*k-3*k,y:this.canvas.i/5,w:3*k,i:3.5*k,color:"gold",ra:"#fff"};this.Ya=[new V(this.Da),new V(this.pa)];this.$=[{K:"m",e:"\ud83d\udd2e",m:W(this,"\ud83d\udd2e",!1),Y:W(this,"\ud83d\udd2e",!0),c:"#f00"},{K:"f",e:"\ud83d\udd25",m:W(this,"\ud83d\udd25",!1),Y:W(this,"\ud83d\udd25",!0),c:"#f00"},
{K:"w",e:"\ud83d\udca7",m:W(this,"\ud83d\udca7",!1),Y:W(this,"\ud83d\udca7",!0),c:"#00f"},{K:"e",e:"\ud83c\udf31",m:W(this,"\ud83c\udf31",!1),Y:W(this,"\ud83c\udf31",!0),c:"#0a0"},{K:"i",e:"\ud83c\udf2a\ufe0f",m:W(this,"\ud83c\udf2a\ufe0f",!1),Y:W(this,"\ud83c\udf2a\ufe0f",!0),c:"#aaa"},{K:"z",e:"\u26a1",m:W(this,"\u26a1",!1),Y:W(this,"\u26a1",!0),c:"#ff0"},{K:"l",e:"\u2600\ufe0f",m:W(this,"\u2600\ufe0f",!1),Y:W(this,"\u2600\ufe0f",!0),c:"#ffb"},{K:"d",e:"\ud83c\udf11",m:W(this,"\ud83c\udf11",!1),
Y:W(this,"\ud83c\udf11",!0),c:"#555"}];this.x=0;this.y=this.canvas.i/2;this.rows=Math.floor(this.canvas.i/this.A/2);this.cols=Math.floor(this.canvas.w/this.A);this.M=null;this.canvas.addEventListener("mousedown",f=>d(f));this.canvas.addEventListener("mouseup",f=>c(f));this.canvas.addEventListener("mousemove",f=>e(f));this.canvas.addEventListener("touchstart",f=>d(f));this.canvas.addEventListener("touchend",f=>c(f));this.canvas.addEventListener("touchmove",f=>e(f));var c=f=>{this.M=null;if(0<this.D.B.length){var g=
Ab(this.D),h=ea.find(m=>m.g==g);if(h){if(h.l)this.D.B.forEach(m=>{this.grid[m.r][m.c].Z=0}),this.grid=Db(this,this.grid,this.rows,this.cols,m=>0==m.Z,(m,p)=>Eb(this,m,p)),Fb(this,this.grid),this.pa.V-=h.j;else{var l=yb(this.D);this.D.B.forEach(m=>{this.grid[m.r][m.c].Z=0});l.Z=h.r;l.v=this.$.find(m=>m.K==h.r).m;this.grid=Db(this,this.grid,this.rows,this.cols,m=>0==m.Z,(m,p)=>Eb(this,m,p));Fb(this,this.grid);this.Da.V-=5}this.Ya=[new V(this.Da),new V(this.pa)]}}this.za=!1;this.D=new Bb;Q(f.touches?
f.touches[0]:f,this.canvas,m=>{this.S.forEach(p=>{p.P&&p.P(m)})})},d=()=>{this.za=!0},e=f=>{Q(f.touches?f.touches[0]:f,this.canvas,g=>{var h=new A(g);g=this.grid.flat().find(n=>E(h,n.s)<this.A/2);if(void 0!=g){var l=g.s;if(this.za){var m=yb(this.D),p=zb(this.D);null==m||void 0==m?this.D.add(g):null!=p&&E(l,p.s)<this.A/2?xb(this.D):E(l,m.s)<1.5*this.A&&this.D.add(g)}}})};Gb(this);this.update(0)}update(){if(0>=this.pa.V)this.sb(this);else{var a=this.canvas.h;this.canvas.fill("#000");a.drawImage(this.pb,
0,0);a.fillStyle="#fff";a.drawImage(this.Ka,this.canvas.w/2-this.Ka.w/2,this.canvas.i/5-this.Ka.i);var b=this.D.getAll();if(1<b.length){var c=Hb(this);a.drawImage(c,this.x+this.w/2-c.w/2,this.y-this.A);a.strokeStyle="#fff";a.lineWidth=this.A/6;a.beginPath();a.moveTo(b[0].s.x,b[0].s.y);for(c=1;c<b.length;c++)a.lineTo(b[c].s.x,b[c].s.y);a.stroke()}for(b=0;b<this.rows;b++)for(c=0;c<this.cols;c++){var d=this.grid[b][c],e=!1;0!=b%2&&0!=c%2||0==b%2&&0==c%2||(e=!0);var f=this.$.find(g=>g.K==d.Z);f&&(e=e?
f.Y:f.m,a.drawImage(e,d.s.x-e.w/2,d.s.y-e.i/2))}this.Ya.forEach(g=>g.L(a));this.S.forEach(g=>g.L(this.canvas.h));requestAnimationFrame(g=>this.update(g))}}}class Jb{constructor(a,b){this.F=a;this.ka=b;a.body.innerHTML="dungeon scene under construction, visit pdemia.com/bcg for updates ^_^ ....";b=O("<button>back</button>");b.onclick=()=>{a.body.innerHTML="";a.body.append(a.canvas);a.I=!1;a.u.remove();a.update(a.time)};a.body.append(b)}update(){}}
class Kb{constructor(a){this.F=a;a.body.innerHTML="";a.body.append(a.canvas);a.I=!1;a.u.remove();I(a.canvas);this.canvas=I(a.canvas);var b=this.canvas.w,c=this.canvas.i;a.body.innerHTML="";a.body.append(this.canvas);var d=this.canvas.h;this.S=[];var e=J("\u25a9",16,"#c3c139",1.3);c=Za(b,c/2,e,"#e7e570");d.drawImage(c,0,0);c=Za(64,64,e,"#c3c139");var f=x("\ud83e\uddd9",64,1.3);d.drawImage(c,b-c.w-16,16);d.drawImage(f,b-c.w-16,16);c=[K("Hello? .....","#7a7818"),K("Portals appear, monsters...","#7a7818"),
K("your master is lost in one of them","#7a7818"),K("your mission ... rescue master","#7a7818"),K("Game is under construction","#00f"),K("JS13k competition 2025","#00f")];b=k;for(var g in c)d.drawImage(c[g],k,b),b+=k;g=K("OK","#7a7818");e=Za(g.w+k,g.i+k,e,"#e7e570");e.h.drawImage(g,k/2,k/2);this.S.push(new r(1.5*k,b,e.w,e.i,e,()=>{a.body.innerHTML="";a.body.append(a.canvas);a.I=!1;a.u.remove();a.update(a.time)}));this.S.forEach(p=>{p.L(d)});this.canvas.addEventListener("mousedown",p=>l(p));this.canvas.addEventListener("mouseup",
p=>h(p));this.canvas.addEventListener("mousemove",p=>m(p));this.canvas.addEventListener("touchstart",p=>l(p));this.canvas.addEventListener("touchend",p=>h(p));this.canvas.addEventListener("touchmove",p=>m(p));var h=p=>{Q(p.touches?p.touches[0]:p,this.canvas,n=>{this.S.forEach(y=>{y.P&&y.P(n)})})},l=()=>{this.za=!0},m=p=>{Q(p.touches?p.touches[0]:p,this.canvas,()=>{})}}}
function oa(a,b){null!=a.u&&a.u.remove();a.u=Object.assign(document.createElement("div"),{className:"menuDialog"});b=O(`<div><h3>Portal Level ${b.level}<h3></div>`);b.style.height=a.canvas.height/2+"px";a.u.append(b);b=Pa(2);b.ia[0][0].innerHTML="<button >Enter</button>";b.ia[0][0].onclick=()=>{a.u.remove();a.I=!0;new Jb(a,a.ka)};b.ia[1][0].innerHTML="<button >Leave</button>";b.ia[1][0].onclick=()=>{a.u.remove()};a.u.append(b);a.body.append(a.u)}
function Lb(a){a.ja=!0;a.I=!0;ub(a);a.canvas=G(a.C.w,a.C.i);a.canvas.fill("#000");Mb(a,a.canvas);a.body.append(a.canvas);X(a)}function Mb(a,b){function c(e){d.update(e);d.L(b);requestAnimationFrame(c)}var d=new Nb(a);d.L(b);requestAnimationFrame(c)}
function X(a){a.I=!0;null!=a.u&&a.u.remove();a.u=Object.assign(document.createElement("div"),{className:"menuDialog"});var b=[];a.ja?(b.push({aa:"<button >New Game</button>",f:"newgame"}),b.push({aa:"<button >Practice Combat</button>",f:"paracticecombat"})):b.push({aa:"<button >Resume</button>",f:"resume"});b.push({aa:"<button> About </button>",f:"about"},{aa:`<button >Music ${a.wa.Ca?"ON":"OFF"}</button>`,f:"music"});a.ja||b.push({aa:"<button >Quit</button>",f:"quit"});var c=Pa(b.length);for(let e in b){var d=
O(b[e].aa);c.ia[e][0].append(d);c.ia[e][0].onclick=()=>{Ob(a,b[e].f)}}a.u.append(c);a.body.append(a.u)}
function Ob(a,b){"newgame"==b?(a.I=!1,a.ja=!1,Pb(a)):"resume"==b?(a.I=!1,a.u.remove(),a.update(a.time)):"music"==b?(a.Ha||(a.Ha=new Oa),a.wa.Ca?Na(a.Ha):Ma(a.Ha),a.wa.Ca=!a.wa.Ca,a.u.remove(),X(a)):"quit"==b?(document.webkitIsFullScreen&&document.exitFullscreen(),a.I=!0,a.ja=!0,a.u.remove(),Lb(a)):"about"==b?(null!=a.u&&a.u.remove(),a.u=Object.assign(document.createElement("div"),{className:"menuDialog"}),a.u.style.width=`${da*k}px`,b=O("<button>Back</button>"),b.onclick=()=>{a.I=!1;a.u.remove();
X(a)},a.u.innerHTML+='\n                <div class="helpDiv" color=\'#fff\'>\n                    <h1>GAME STILL UNDER CONSTRUCTION</h1>\n                    <h3>entry in js13k games 2025</h3>\n                    <h3>visit <a href="https://pdemia.com/bcg">pdemia.com/bcg<a> for updates</h3>\n                    <h3>last update 12/9/2025 </h3>\n                    <p>mohammad0jawad@gmail.com</p>\n                </div>\n            ',a.u.querySelector(".helpDiv").style["overflow-y"]="auto",a.u.append(b),
a.body.append(a.u)):"paracticecombat"==b&&(a.I=!0,a.u.remove(),new Ib(a,()=>{console.log("combat training over");a.I=!0;a.ja=!0;a.u.remove();Lb(a)}))}
function Pb(a){ub(a);a.body.innerHTML="";a.ya=new za(a);a.Cb=a.ya.hb.map(d=>new na(a,d));a.canvas=G(a.C.w,a.C.i);a.body.innerHTML="";a.body.appendChild(a.canvas);a.body.appendChild(a.cb);a.ka=new wb(a);a.S=[new r(0,0,1.5*k,1.5*k,x("\ud83d\udccb",1.5*k,1.4),()=>{X(a)})];a.B=[a.ka,...a.Cb];a.body.innerHTML="";a.body.appendChild(a.canvas);a.body.appendChild(a.cb);a.update(0);new Kb(a);a.M=null;a.canvas.addEventListener("mousedown",d=>b(d));a.canvas.addEventListener("mouseup",()=>{a.M=null});a.canvas.addEventListener("mousemove",
d=>c(d));a.canvas.addEventListener("touchstart",d=>b(d));a.canvas.addEventListener("touchend",()=>{a.M=null});a.canvas.addEventListener("touchmove",d=>c(d));var b=d=>{Q(d.touches?d.touches[0]:d,a.canvas,e=>{a.M={x:e.x,y:e.y}})},c=d=>{a.M&&Q(d.touches?d.touches[0]:d,a.canvas,e=>{a.M={x:e.x,y:e.y}})}}
class Qb extends vb{constructor(){super();this.C={w:600,i:600};Ua(a=>{this.Fa=new sb(a);this.B=[];Lb(this)})}update(a){if(1!=this.I){if(1==this.ja)return this.Ib();this.B.forEach(d=>d.update(a));var b=I(this.ya.map),c=b.h;this.B.sort((d,e)=>{let f,g;return d.Ea?null==(f=d.Ea)?void 0:f.y:Infinity-e.Ea?null==(g=e.Ea)?void 0:g.y:Infinity});this.B.forEach(d=>d.L(c));b=P(b,Math.max(0,this.ka.s.x-this.C.w/2),Math.max(0,this.ka.s.y-this.C.i/2),this.C.w,this.C.i);this.canvas.fill("#88bfff");this.canvas.h.drawImage(b,
0,0);this.canvas.h.fillRect;this.S.forEach(d=>d.L(this.canvas.h));this.M&&(this.B.forEach(d=>{d.P&&d.P(this.M)}),this.S.forEach(d=>{d.P&&d.P(this.M)}),this.M=null);this.time=a;requestAnimationFrame(d=>this.update(d))}}}function Rb(a){var b="THE FAMILIAR".split(""),c=G(64*b.length,k+4),d=0;for(let g in b){var e=J(b[g],k,"#fff",1.1,"cursive"),f=J(b[g],k,"#b90000",1.1,"cursive");c.h.drawImage(e,d+1,1);c.h.drawImage(f,d,0);d+=k}a.H={v:c,fb:128,gb:a.Ta,ha:0}}
class Nb{constructor(a){this.F=a;this.la=new Fa(a);this.bb=J("BY MHMDJAWADZD",16,"#fff",1.5,"cursive");this.Za=this.la.U[0];this.$a=Xa(this.Za);this.$a.h.drawImage(this.Za,1,1);this.canvas=G(a.C.w,a.C.i);$a(this.$a);this.ta=Ea(this.la);this.ab=this.ta.map(c=>Xa(c));this.ab.forEach((c,d)=>c.h.drawImage(this.ta[d],1,1));this.qb=this.ab.map(c=>$a(c));this.nb=Ta(3*this.canvas.w,this.canvas.i);this.X=5;this.elements=[{m:x("\ud83d\udd25",32,1.3),c:"#ee4000c7",g:0,t:this.X},{m:x("\ud83d\udca7",32,1.3),c:"#00c7eec7",
g:10,t:this.X},{m:x("\ud83c\udf31",32,1.3),c:"#805a05c7",g:20,t:this.X},{m:x("\ud83c\udf2a\ufe0f",32,1.3),c:"#cdcf84c7",g:30,t:this.X},{m:x("\u26a1",32,1.3),c:"#f9ff30c7",g:40,t:this.X},{m:x("\u2600\ufe0f",32,1.3),c:"#f8ff00c7",g:50,t:this.X},{m:x("\ud83c\udf11",32,1.3),c:"#a83bf3c7",g:60,t:this.X}];this.ga=Ra(4*k,"#fff",null,3);Ra(k/9,"#00f","#00f",3);a=this.canvas.i-this.ga.i/2-k;var b={x:this.canvas.w/2,y:a,r:this.ga.w/2};this.va=fa(b.x,b.y,b.r);this.ua=b;this.Ta=a-this.ga.i/2-k;this.N={ob:this.qb,
current:0,frames:0,framerate:16,fb:64,gb:this.Ta};Rb(this)}L(a){a.h.drawImage(this.canvas,0,0)}update(){this.canvas.h.drawImage(this.nb,0,0,U(0,this.nb.w-this.canvas.w),this.canvas.i,0,0,this.canvas.w,this.canvas.i);this.canvas.h.drawImage(this.ga,this.ua.x-this.ga.w/2,this.ua.y-this.ga.i/2);this.canvas.h.drawImage(this.N.ob[this.N.current],this.ua.x-32,this.ua.y-32);this.N.frames++;this.N.frames>this.N.framerate&&(this.N.frames=0,this.N.current++,this.N.current>=this.N.ob.length&&(this.N.current=
0));this.canvas.h.drawImage(this.H.v,0,0,this.H.ha,this.H.v.i,this.H.fb,this.H.gb,this.H.ha,this.H.v.i);this.H.ha+=4;this.H.ha>this.H.v.w&&(this.H.ha=0);this.elements.forEach(a=>{var b=this.va[a.g%this.va.length];this.canvas.h.drawImage(a.m,b.x-a.m.w/2,b.y-a.m.i/2);var c=this.elements.filter(d=>d!=a)[U(this.elements.length-1)];c=this.va[c.g%this.va.length];this.canvas.h.save();this.canvas.h.strokeStyle=a.c;this.canvas.h.lineWidth=2;this.canvas.h.beginPath();this.canvas.h.moveTo(b.x,b.y);this.canvas.h.lineTo(c.x,
c.y);this.canvas.h.stroke();this.canvas.h.restore();a.t--;0>=a.t&&(a.t=this.X,a.g++)});this.canvas.h.drawImage(this.bb,0,this.canvas.i-this.bb.i)}}document.addEventListener("DOMContentLoaded",function(){window.F=new Qb},!1);
