let m=32;
var q={Ya:[{h:[0,0,140,0,0,0,140,0,0,255,158,158,158,0,0,0,0,51,2,1,2,58,239,0,32,88,1,157,2],p:[1,1,1,1],c:[{n:[161,,,,,,,,,,,,,,,,163,,,,,,,,159],f:[]}]},{h:[0,91,128,0,0,95,128,12,0,0,12,0,72,0,0,0,0,0,0,0,2,255,0,0,32,83,3,130,4],p:[1,1,2,1],c:[{n:[144,,151,,149,,147,,146,,147,,146,,144,,144,,151,,149,,147,,146,,147,,146,,144],f:[]},{n:[156,,163,,161,,159,,158,,159,,158,,156,,156,,163,,161,,159,,158,,159,,158,,168],f:[]}]},{h:[0,16,133,0,0,28,126,12,0,0,2,0,60,0,0,0,0,0,0,0,2,91,0,0,32,47,3,157,
2],p:[1,2,1,2],c:[{n:[144,,151,,149,,147,,146,,147,,146,,144,,144,,151,,149,,147,,146,,147,,146,,144],f:[]},{n:[168,,175,,173,,171,,170,,171,,170,,168,,168,,175,,173,,171,,170,,171,,170,,168],f:[]}]},{h:[0,255,116,79,0,255,116,0,83,0,4,6,69,52,0,0,0,0,0,0,2,14,0,0,32,0,0,0,0],p:[1,1,1,1],c:[{n:[144,,151,,149,,147,,146,,147,,146,,144,,144,,151,,149,,147,,146,,147,,146,,144,,,159,,,,159,,,,159,,,,,,,,,,,,159,,159],f:[]}]}],Ia:8269,Ha:32,Oa:3,Sa:4};
function aa(a){function b(z){return x(d,z[0],z[1],z[2],z[3])}function c(z,B,I,D,C){var v=A(d);v.g.drawImage(k,e.na[0],e.na[1]+(z?-2:0));v.g.drawImage(n,e.ta[0],e.ta[1]+(B?-2:0));I?v.g.drawImage(g,e.$[0],e.$[1]+4):v.g.drawImage(f,e.$[0],e.$[1]);D?v.g.drawImage(r,e.V[0],e.V[1]-4):v.g.drawImage(t,e.V[0],e.V[1]);C?v.g.drawImage(y,e.Z[0],e.Z[1]-4):v.g.drawImage(l,e.Z[0],e.Z[1]);return v}var d=A(a.La);a=[];var e={$:[27,20,4,6],na:[7,29,8,3],ta:[17,29,8,3],V:[5,15,5,7],Z:[22,15,5,7]},f=b(e.$),g=F(f),k=b(e.na),
n=b(e.ta),t=b(e.V),r=F(t),l=b(e.Z),y=F(l);for(var u in e){var p=e[u];d.g.clearRect(p[0],p[1],p[2],p[3])}u=[{K:0,M:0,N:0,J:0,L:0},{K:0,M:0,N:0,J:0,L:0},{K:1,M:0,N:0,J:0,L:1},{K:1,M:0,N:1,J:0,L:0},{K:0,M:1,N:0,J:1,L:0},{K:0,M:1,N:1,J:0,L:0}];for(let z in u)p=u[z],p=c(p.K,p.M,p.N,p.J,p.L),a.push(p);return a}class ba{constructor(a){a=A(a);a=H(a,b=>""==b||"#fff"==b||"#ffffff"==b?null:b);a=ca(a);this.La=x(a,0,0,32,32);x(a,32,0,32,32);this.Da=x(a,0,32,64,64)}}
class ma{constructor(a){var b=m,c=m,d=K("\ud83d\udccb",m,1.4);this.y=this.x=0;this.w=b;this.i=c;this.A=d;this.onclick=a}T(a){var b=a.x;a=a.y;if(b>=this.x&&b<=this.x+this.w&&a>=this.y&&a<=this.y+this.i){if(this.onclick)this.onclick(this);return!0}return!1}I(a){a.save();a.strokeStyle="#f00";a.lineWidth=2;a.strokeRect(this.x,this.y,this.w,this.i);a.restore();a.drawImage(this.A,this.x,this.y,this.w,this.i)}update(){}}
function na(a,b){let c=a[0],d=b[c[0]][c[1]];for(const e of a){const [f,g]=e;b[f][g]<d&&(c=e,d=b[f][g])}return c}function oa(a,b){const c=[b];for(;a.hasOwnProperty(`${b[0]}-${b[1]}`);)b=a[`${b[0]}-${b[1]}`],c.unshift(b);return c}function pa(a,b,c){const d=[];0<b&&d.push([b-1,c]);b<a.rows-1&&d.push([b+1,c]);0<c&&d.push([b,c-1]);c<a.cols-1&&d.push([b,c+1]);return d}
function qa(a,b,c,d,e){b=Math.floor(b);c=Math.floor(c);d=Math.floor(d);e=Math.floor(e);const f=[],g=new Set,k={},n=Array(a.rows).fill(null).map(()=>Array(a.cols).fill(Infinity));n[b][c]=0;const t=Array(a.rows).fill(null).map(()=>Array(a.cols).fill(Infinity));t[b][c]=Math.abs(b-d)+Math.abs(c-e);for(f.push([b,c]);0<f.length;){b=na(f,t);const [r,l]=b;if(r===d&&l===e)return oa(k,b);f.splice(f.indexOf(b),1);g.add(`${r}-${l}`);c=pa(a,r,l);for(const y of c){const [u,p]=y;g.has(`${u}-${p}`)||a.Ra[u][p]||
(c=n[r][l]+1,c<n[u][p]&&(k[`${u}-${p}`]=b,n[u][p]=c,t[u][p]=c+(Math.abs(u-d)+Math.abs(p-e)),f.includes(y)||f.push(y)))}}return null}class ra{constructor(a){this.Ra=a;this.rows=a.length;this.cols=a[0].length}}function sa(a=64,b=64){const c=L(a,b),d=c.g;d.fillStyle="#a67c52";d.fillRect(0,0,a,b);for(let e=0;e<a+b;e++){const f=N(0,a),g=N(0,b),k=N(2,5);d.globalAlpha=O(.15,.35);d.fillStyle=.5<O()?"#c2b280":"#7c5c36";d.beginPath();d.arc(f,g,k,0,2*Math.PI);d.fill()}d.globalAlpha=1;return c}
function ta(a=64,b=64){const c=L(a,b),d=c.g;d.fillStyle="#b0a99f";d.fillRect(0,0,a,b);const e=a/4;b/=4;for(let f=0;4>f;f++)for(let g=0;4>g;g++){let k=g*e+(1===f%2?e/2:0);if(k+e>a)continue;let n=f*b;d.fillStyle=.5<O()?"#d6d2c4":"#a59e91";d.fillRect(k,n,e-2,b-2);d.strokeStyle="#8d867a";d.lineWidth=1;d.strokeRect(k,n,e-2,b-2)}d.globalAlpha=1;return c}
function ua(a=64,b=64){const c=L(a,b),d=c.g;d.fillStyle="#639bff";d.fillRect(0,0,a,b);for(let e=0;e<a+b;e++){const f=N(0,a),g=N(0,b),k=N(2,6);d.globalAlpha=O(.15,.35);d.fillStyle="#a3d8ff";d.beginPath();d.arc(f,g,k,0,2*Math.PI);d.fill()}d.globalAlpha=1;return c}function va(a,b){var c=wa(),d={};a.ya.map(f=>d[f.c]=f.s);a=H(b,f=>""==f?null:f);b=L(64*m,64*m);var e=b.g;e.drawImage(c,0,0);for(let f=0;64>f;f++)for(let g=0;64>g;g++)c=d[a[g][f]],void 0!=c&&e.drawImage(c,f*m,g*m);return b}
function xa(a,b){var c={};for(var d in b)c[b[d].c]=b[d].o;b=[];for(d=0;d<a.length;d++){b[d]=[];for(var e=0;e<a[d].length;e++){var f=c[a[e][d]];b[d][e]=void 0!=f&&0==f?0:1}}return b}function ya(a=64,b=64){const c=L(a,b),d=c.g;d.fillStyle="#4caf50";d.fillRect(0,0,a,b);for(let e=0;e<a+b;e++){const f=N(0,a),g=N(0,b),k=N(2,5);d.globalAlpha=O(.18,.38);d.fillStyle=.5<O()?"#81c784":"#388e3c";d.beginPath();d.arc(f,g,k,0,2*Math.PI);d.fill()}d.globalAlpha=1;return c}
function wa(){var a=64*m,b=64*m,c=m*m,d=[K("\ud83c\udf39",12,1.3),K("\ud83c\udf37",12,1.3),K("\ud83c\udf3b",12,1.3),K("\ud83c\udf3c",12,1.3),K("\ud83c\udf31",12,1.3)];const e=L(a,b);var f=e.g,g=ya(a,b);f.fillStyle="#4caf50";f.drawImage(g,0,0);for(g=0;g<c;g++)f.drawImage(d[N(0,d.length)],N(0,a-12),N(0,b-12));return e}
class za{constructor(a){this.F=a;this.Aa=this.F.l.w;this.ch=this.F.l.i;var b=sa(m,m),c=ta(m,m),d=ua(m,m),e=K("\ud83c\udf33",m,1.3),f=K("\ud83c\udfe1",2*m,1.3),g=K("\ud83c\udfe0",2*m,1.3),k=K("\u26ea",3*m,1.3),n=K("\ud83c\udfeb",3*m,1.3),t=K("\ud83c\udff0",4*m,1.3),r=K("\ud83c\udfea",3*m,1.3),l=K("\u26fa",3*m,1.3),y=Aa();this.ya=[{c:"#99e550",o:0,v:"",s:void 0},{c:"#639bff",o:1,v:"",s:d},{c:"#6abe30",o:1,v:"",s:e},{c:"#76428a",o:1,v:"house1",s:f},{c:"#d77bba",o:1,v:"house2",s:g},{c:"#d9a066",o:0,v:"",
s:b},{c:"#767676",o:1,v:"",s:y},{c:"#df7126",o:1,v:"castle",s:t},{c:"#8f974a",o:1,v:"church",s:k},{c:"#fbf236",o:1,v:"townhall",s:n},{c:"#ac3232",o:1,v:"store",s:r},{c:"#663931",o:0,v:"",s:c},{c:"#524b24",o:1,v:"tent",s:l}];this.Ma=H(a.ua.Da,u=>""==u?null:u);this.map=va(this,a.ua.Da);this.Ga=xa(this.Ma,this.ya);this.Wa=new ra(this.Ga)}I(a){let b=this.map,c;let d,e,f,g;var k=NaN-this.ch/2;c=NaN-this.Aa/2;0>=c&&(c=0);0>=k&&(k=0);c+this.w>b.width&&(c=b.width-this.Aa);k+this.i>b.height&&(k=b.height-this.ch);
d=f=this.w;e=g=this.i;a.drawImage(b,c,k,d,e,0,0,f,g)}}function Ba(a){return[a.la[0],a.la[1]]}function Ca(a){var b=[];for(let c=2;5>=c;c++)b.push(a.la[c]);return b}class Da{constructor(a){this.la=aa(a.ua)}}function Ea(a){a.X=q;a.oa=q.Oa;a.fa=0;a.W=q.Ia*q.Ha*(a.oa+1)*2;a.G=new Int32Array(a.W)}
function Fa(a,b,c){Ea(a);var d=()=>{var e,f,g,k,n,t,r=new Int32Array(a.W);const l=a.X.Ya[a.fa],y=a.X.Ia,u=a.X.Ha;let p=0,z=0;var B=!1;const I=[];for(g=0;g<=a.oa;++g){var D=l.p[g];for(k=0;k<u;++k){if(t=D?l.c[D-1].f[k]:0)l.h[t-1]=l.c[D-1].f[k+u]||0,17>t&&(I.length=0);const La=a.pa[l.h[16]],Ma=l.h[17]/512,Na=2**(l.h[18]-9)/y,Oa=l.h[19],da=l.h[20],Pa=135.82764118168*l.h[21]/44100,Qa=1-l.h[22]/255,T=1E-5*l.h[23],Ra=l.h[24]/32,Sa=l.h[25]/512,Ta=6.283184*2**(l.h[26]-9)/y,ea=l.h[27]/255,U=l.h[28]*y&-2;t=
(g*u+k)*y;for(n=0;4>n;++n)if(f=D?l.c[D-1].n[k+n*u]:0){if(!I[f]){var C=e=f;var v=a.pa[l.h[0]];const Ua=l.h[1],Va=l.h[3]/32,Wa=a.pa[l.h[4]],Xa=l.h[5],Ya=l.h[8]/32,fa=l.h[9],J=l.h[10]*l.h[10]*4,P=l.h[11]*l.h[11]*4,V=l.h[12]*l.h[12]*4,Za=1/V,$a=-l.h[13]/16;let M=l.h[14];const ab=y*2**(2-l.h[15]),ha=new Int32Array(J+P+V);let ia=0,ja=0,ka=0,la=0;for(let G=0,W=0;G<J+P+V;G++,W++){0<=W&&(M=M>>8|(M&255)<<4,W-=ab,ka=.003959503758*2**((C+(M&15)+l.h[2]-128-128)/12),la=.003959503758*2**((C+(M&15)+l.h[6]-128-128)/
12)*(1+8E-4*l.h[7]));let E=1;G<J?E=G/J:G>=J+P&&(E=(G-J-P)*Za,E=(1-E)*3**($a*E));ia+=ka*E**Va;let X=v(ia)*Ua;ja+=la*E**Ya;X+=Wa(ja)*Xa;fa&&(X+=(2*Math.random()-1)*fa);ha[G]=80*X*E|0}I[e]=ha}C=I[f];f=0;for(e=2*t;f<C.length;f++,e+=2)r[e]+=C[f]}for(f=0;f<y;f++)n=2*(t+f),(e=r[n])||B?(B=Pa,Oa&&(B*=La(Na*n)*Ma+.5),B=1.5*Math.sin(B),p+=B*z,e=Qa*(e-z)-p,z+=B*e,e=3==da?z:1==da?e:p,T&&(e*=T,e=1>e?-1<e?a.Fa(.25*e):-1:1,e/=T),e*=Ra,B=1E-5<e*e,C=Math.sin(Ta*n)*Sa+.5,v=e*(1-C),e*=C):v=0,n>=U&&(v+=r[n-U+1]*ea,e+=
r[n-U]*ea),r[n]=v|0,r[n+1]=e|0,a.G[n]+=v|0,a.G[n+1]+=e|0}}a.fa++;if(1==a.fa/a.X.Sa){g=b.createBuffer(2,a.W/2,44100);for(k=0;2>k;k++)for(D=g.getChannelData(k),r=k;r<a.W;r+=2)D[r>>1]=a.G[r]/65536;return c(g)}requestAnimationFrame(d)};requestAnimationFrame(d)}
class Ga{constructor(){this.pa=[this.Fa,this.Ua,this.Ta,this.Va];this.X=null;this.W=this.fa=this.oa=0;this.G=null}Fa(a){return Math.sin(6.283184*a)}Ta(a){return a%1*2-1}Ua(a){return.5>a%1?1:-1}Va(a){a=a%1*4;return 2>a?a-1:3-a}getData(a,b){const c=2*Math.floor(44100*a),d=Array(b);for(let e=0;e<2*b;e+=1){const f=c+e;d[e]=0<a&&f<this.G.length?this.G[f]/32768:0}return d}}
function Ha(a){const b=a.C.sampleRate;a=a.C.createBuffer(1,.3*b,b).getChannelData(0);for(var c=0;c<a.length;c++)a[c]=2*(Math.random()-.5);c=.29-.1;for(let d=0;d<a.length;d++){let e=d/b;.01>e?a[d]*=e/.01:.11>e?a[d]*=1-(e-.01)/.1*.8:e>.3-c&&(a[d]*=(.3-e)/c)}for(c=0;c<a.length;c++)a[c]*=Math.sin(c/b*Math.PI*2*(440+100*Math.random()))}
function Ia(a){const b=a.C.sampleRate;a=a.C.createBuffer(1,.5*b,b).getChannelData(0);for(var c=0;c<a.length;c++)a[c]=2*Math.random()-1;for(c=0;c<a.length;c++){let d=c/b;.05>d?a[c]*=d/.05:.25>d?a[c]*=1-(d-.05)/.2:.25<d&&(a[c]*=(.5-d)/.25)}}function Ja(a){a.B&&(a.B.stop(),a.B=null);a.xa&&(a.B=a.C.createBufferSource(),a.B.buffer=a.xa,a.B.connect(a.C.destination),a.B.loop=!0,a.B.start(0,a.ra),a.startTime=a.C.currentTime-a.ra)}
class Ka{constructor(){this.C=new (window.AudioContext||window.webkitAudioContext);new (window.AudioContext||window.webkitAudioContext);Ha(this);Ia(this);var a=new Ga;this.startTime=this.ra=0;Fa(a,this.C,b=>{this.xa=b;Ja(this)})}}function A(a){var b=L(a.width,a.height);b.g.drawImage(a,0,0);return b}
function H(a,b){for(var c=a.getContext("2d").getImageData(0,0,a.width,a.height).data,d=[],e=0;e<c.length;e+=4){var f=d,g=f.push;var k=c[e];var n=c[e+1],t=c[e+2];k=0==k+n+t+c[e+3]?null:0==k+n+t||255<k||255<n||255<t?"#000000":"#"+((k<<16)+(n<<8)+t).toString(16).padStart(6,"0");g.call(f,k)}c=[];for(e=0;e<a.height;e++)c[e]=[];f=e=0;for(g=0;g<d.length;g++)e>=a.width&&(f++,e=0),c[f][e]=d[g],b&&(c[f][e]=b(c[f][e])),e++;return c}
function ca(a){let b=a.length,c=Math.max(...a.map(g=>g.length));var d=L(1*c,1*b),e=d.g;for(let g=0;g<b;g++)for(let k=0;k<c;k++){var f=a[g][k];f&&""!=f&&(e.fillStyle=f,e.fillRect(1*k,1*g,1,1))}return d}function x(a,b,c,d,e){let f=L(d,e);f.g.drawImage(a,b,c,d,e,0,0,d,e);return f}function F(a){let b=L(a.width,a.height),c=b.g;c.save();c.scale(1,-1);c.drawImage(a,0,0,a.width,-1*a.height);c.restore();return b}
function K(a,b,c=1.3,d="#000",e="sans-serif"){let f=L(b,b);var g=f.g;g.font=`${b/c}px ${e}`;g.textAlign="center";g.textBaseline="middle";g.fillStyle=d;g.fillText(a,b/2,1.1*b/2);return f}
function Aa(){var a=L(8,8),b=a.g;b.fillStyle="#afafaf";b.fillRect(0,0,a.width,a.height);b.fillStyle="#6d6c6c";b.fillRect(7,0,1,4);b.fillRect(0,3,8,1);b.fillRect(4,4,1,4);b.fillRect(0,7,8,1);b=4;0==b&&(b=4);b=L(a.width*b,4*a.height);a=b.g.createPattern(a,"repeat");b.g.fillStyle=a;b.g.fillRect(0,0,b.w,b.i);return b}
function L(a=0,b=0){let c=document.createElement("canvas");c.width=a;c.height=b;c.w=a;c.i=b;c.g=c.getContext("2d");c.m={x:a/2,y:b/2};c.clear=()=>{c.g.clearRect(0,0,a,b)};c.fill=d=>{c.g.fillStyle=d;c.g.fillRect(0,0,a,b)};c.$a=d=>{d=c.g.createPattern(d,"repeat");c.g.fillStyle=d;c.g.fillRect(0,0,a,b)};return c}function N(a=1,b=0){return O(a,b)|0}function O(a=1,b=0){return b+(a-b)*Math.random()}
function bb(a){var b="";for(var c=0;c<a;c++){b+="<tr>";for(var d=0;1>d;d++)b+="<td></td>";b+="</tr>"}a=document.createElement("table");a.innerHTML=b;b=[];c=a.querySelectorAll("tr");for(let e=0;e<c.length;e++)d=c[e].querySelectorAll("td"),d.forEach(f=>f.U=g=>f.innerHTML=g),b[e]=[...d];a.Ba=b;return a}function Q(a,b,c,d=.8){a=a.toUpperCase();let e=L(b*a.length,b);for(let g=0;g<a.length;g++){var f=K(a[g],b,d,c,"cursive");e.g.drawImage(f,g*b,0)}return e}
function R(a){var b=document.createElement("div");b.innerHTML=a;return b.firstChild}function cb(a=8,b=8){var c=L(a,b),d=c.g;d.fillStyle="#aaa";d.fillRect(0,0,c.width,c.height);d.fillStyle="#fff";for(let e=0;e<b;e++)for(let f=0;f<a;f++).001>Math.random()&&d.fillRect(f,e,1,1);return c}function db(a){var b="sh1.gif?"+Math.random(),c=new Image;c.src=b;c.addEventListener("load",()=>{a(c)})}function eb(a){var b=m;return parseInt(a/b)*b+b/2}
function fb(a,b,c){var d=b.getBoundingClientRect();c(new S({x:b.width/d.width*(a.clientX-d.left)+window.scrollX,y:b.height/d.height*(a.clientY-d.top)+window.scrollY}))}function gb(a,b,c=1){var d=a.y==b.y?0:a.y<b.y?c:-c;a.x+=a.x==b.x?0:a.x<b.x?c:-c;a.y+=d}function hb(a,b){let c;c=0+Math.pow(a.x-b.x,2);c+=Math.pow(a.y-b.y,2);return c=Math.sqrt(c)}class S{constructor(a){this.x=a.x;this.y=a.y}}
function Y(a){a.layout=R("<div class='layout'></div>");a.Qa=R("<div class='header'></div>");a.body=R("<div class='body'></div>");a.Pa=R("<div class='footer'></div>");a.layout.appendChild(a.Qa);a.layout.appendChild(a.body);a.layout.appendChild(a.Pa);document.body.innerHTML="";document.body.appendChild(a.layout)}
class ib{constructor(){this.ca={ha:!1,bb:!1,controls:!1};Y(this);var a=R("<div>Loading....</div>");this.body.append(a);this.Za=window.innerHeight/window.innerWidth;1<this.Za&&(m=32);this.Ca=document.createElement("div");document.body.innerHTML=""}}
class jb{constructor(a){this.F=a;this.speed=2;this.P=new Da(a);this.aa=Ba(this.P);this.ba=Ca(this.P);this.animation={framerate:8,frame:0,ja:0,va:this.aa};this.m=new S({x:3*m-m/2,y:5*m-m/2});this.ia=new S(this.m);this.A=this.aa[0];this.ga=!1;this.destination=new S(this.m);this.qa=[]}update(){this.animation.va=this.ga?this.ba:this.aa;this.animation.frame++;this.animation.frame>=this.animation.framerate&&(this.animation.ja>=this.animation.va.length&&(this.animation.ja=0),this.A=this.animation.va[this.animation.ja],
this.animation.ja++,this.animation.frame=0);hb(this.destination,this.m)>=this.speed?gb(this.m,this.destination,this.speed):(this.m=new S(this.destination),this.ga=!1);if(0==hb(this.destination,this.m)&&0<this.qa.length){var a=this.qa.shift();this.destination=new S(a);this.ga=!0}}I(a){a.drawImage(this.A,this.m.x-this.A.w/2,this.m.y-this.A.i/2)}T(a){if(!(a.y<m)){var b=Math.floor(eb(Math.max(0,this.m.x-this.F.l.w/2)+a.x)/m);a=Math.floor(eb(Math.max(0,this.m.y-this.F.l.i/2)+a.y)/m);var c;if(c=0==this.ga){try{var d=
1==this.F.ma.Ga[b][a]}catch(e){d=!0}c=!d}if(c){b=qa(this.F.ma.Wa,Math.floor(this.m.x/m),Math.floor(this.m.y/m),b,a);d=[];if(1<b.length)for(c=1;c<b.length;c++)a=b[c],d.push(new S({x:a[0]*m+m/2,y:a[1]*m+m/2}));this.qa=d}}}}function kb(a){a.S=!0;a.R=!0;Y(a);var b=L(a.l.w,a.l.i);b.fill("#000");lb(a,b);a.body.append(b);Z(a)}function lb(a,b){function c(e){d.update(e);d.I(b);requestAnimationFrame(c)}var d=new mb(a);d.I(b);requestAnimationFrame(c)}
function Z(a){a.R=!0;null!=a.H&&a.H.remove();a.H=Object.assign(document.createElement("div"),{className:"menuDialog"});var b=[];a.S?b.push({U:"<button >New Game</button>",f:"newgame"}):b.push({U:"<button >Resume</button>",f:"resume"});b.push({U:`<button >Music ${a.ca.ha?"ON":"OFF"}</button>`,f:"music"});a.S||b.push({U:"<button >Quit</button>",f:"quit"});var c=bb(b.length);for(let e in b){var d=R(b[e].U);d.style.width=`${.9*a.l.w}px`;d.style.fontSize="24pt";c.Ba[e][0].append(d);c.Ba[e][0].onclick=
()=>{var f=b[e].f;"newgame"==f?(a.R=!1,a.S=!1,nb(a)):"resume"==f?(a.R=!1,a.H.remove(),a.update(a.time)):"music"==f?(a.ka||(a.ka=new Ka),a.ca.ha?(f=a.ka,f.B&&(f.ra=f.C.currentTime-f.startTime,f.B.stop(),f.B=null)):Ja(a.ka),a.ca.ha=!a.ca.ha,a.H.remove(),Z(a)):"quit"==f&&(document.webkitIsFullScreen&&document.exitFullscreen(),a.R=!0,a.S=!0,a.H.remove(),kb(a))}}a.H.append(c);a.body.append(a.H)}
function nb(a){Y(a);a.body.innerHTML="";a.ma=new za(a);a.canvas=L(a.l.w,a.l.i);a.body.innerHTML="";a.body.appendChild(a.canvas);a.body.appendChild(a.Ca);a.sa=new jb(a);a.Ea=[new ma(()=>{Z(a)})];a.Y=[a.sa];a.body.innerHTML="";a.body.appendChild(a.canvas);a.body.appendChild(a.Ca);a.update(0);window.addEventListener("keyup",d=>{"Escape"==d.key&&Z(a)});a.D=null;a.canvas.addEventListener("mousedown",d=>b(d));a.canvas.addEventListener("mouseup",()=>{a.D=null});a.canvas.addEventListener("mousemove",d=>c(d));
a.canvas.addEventListener("touchstart",d=>b(d));a.canvas.addEventListener("touchend",()=>{a.D=null});a.canvas.addEventListener("touchmove",d=>c(d));var b=d=>{fb(d.touches?d.touches[0]:d,a.canvas,e=>{a.D={x:e.x,y:e.y}})},c=d=>{a.D&&fb(d.touches?d.touches[0]:d,a.canvas,e=>{a.D={x:e.x,y:e.y}})}}
class ob extends ib{constructor(){super();this.l={w:600,i:600};document.body.append(K("\ud83d\udc08\u200d\u2b1b",32,1.3));db(a=>{this.ua=new ba(a);this.Y=[];kb(this)})}update(a){if(1!=this.R){if(1==this.S)return this.ab();this.Y.forEach(d=>d.update(a));var b=A(this.ma.map),c=b.g;this.Y.sort((d,e)=>{let f,g;return d.ia?null==(f=d.ia)?void 0:f.y:Infinity-e.ia?null==(g=e.ia)?void 0:g.y:Infinity});this.Y.forEach(d=>d.I(c));b=x(b,Math.max(0,this.sa.m.x-this.l.w/2),Math.max(0,this.sa.m.y-this.l.i/2),this.l.w,
this.l.i);this.canvas.fill("#fff");this.canvas.g.drawImage(b,0,0);this.canvas.g.fillRect;this.Ea.forEach(d=>d.I(this.canvas.g));this.D&&(this.Y.forEach(d=>{d.T&&d.T(this.D)}),this.Ea.forEach(d=>{d.T&&d.T(this.D)}),this.D=null);this.time=a;requestAnimationFrame(d=>this.update(d))}}}function pb(a){var b="FAMILIAR".split(""),c=L(64*b.length,m+4),d=0;for(let g in b){var e=Q(b[g],m,"#fff",1.1),f=Q(b[g],m,"#b90000",1.1);c.g.drawImage(e,d+1,1);c.g.drawImage(f,d,0);d+=m}a.u={A:c,da:128,ea:a.wa,O:0}}
class mb{constructor(a){this.P=new Da(a);this.aa=Ba(this.P);this.ba=Ca(this.P);this.Na=this.ba.map(b=>{var c=L(b.w,b.i);c.fill("#fff");let d=L(b.width,b.height),e=d.g;e.drawImage(b,0,0);e.globalCompositeOperation="source-atop";for(let f=0;f<b.width/c.width;f++)for(let g=0;g<b.height/c.height;g++)e.drawImage(c,f*c.width,g*c.height);b=L(b.w+2,b.i+2);b.g.drawImage(d,0,0,b.w,b.i);return b});this.canvas=L(a.l.w,a.l.i);this.za=Q("BY MHMDJAWADZD",16,"#fff",1.5);this.Ja=cb(3*this.canvas.w,this.canvas.i);
this.wa=this.canvas.i/2+64;this.j={Ka:this.ba,Xa:this.Na,current:0,frames:0,framerate:16,da:64,ea:this.wa};pb(this)}I(a){a.g.drawImage(this.canvas,0,0)}update(){this.canvas.g.drawImage(this.Ja,0,0,N(0,this.Ja.w-this.canvas.w),this.canvas.i,0,0,this.canvas.w,this.canvas.i);this.canvas.g.drawImage(this.za,0,this.canvas.i-this.za.i);this.canvas.g.drawImage(this.j.Xa[this.j.current],this.j.da-1,this.j.ea-1);this.canvas.g.drawImage(this.j.Ka[this.j.current],this.j.da,this.j.ea);this.j.frames++;this.j.frames>
this.j.framerate&&(this.j.frames=0,this.j.current++,this.j.current>=this.j.Ka.length&&(this.j.current=0));this.canvas.g.drawImage(this.u.A,0,0,this.u.O,this.u.A.i,this.u.da,this.u.ea,this.u.O,this.u.A.i);this.u.O+=4;this.u.O>this.u.A.w&&(this.u.O=0)}}document.addEventListener("DOMContentLoaded",function(){window.F=new ob},!1);
